In [ ]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.15.0
access                                1.1.10.post3
affine                                3.0.1
aiofiles                              25.1.0
aiohappyeyeballs                      2.7.1
aiohttp                               3.14.3
aiosignal                             1.4.0
aiosqlite                             0.22.1
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.12.1
altair                                5.5.0
annotated-doc                         0.0.5
annotated-types                       0.8.0
antlr4-python3-runtime                4.9.3
anyio                                 4.15.1
anywidget                             0.9.21
apsw                                  3.53.4.0
argon2-cffi                           25.1.0
argon2-cffi-bindings                  26.1.0
array_record                          0.8.3
arrow                                 1.4.0
arviz                                 0.22.0
astropy                               7.2.2
astropy-iers-data                     0.2026.9.28.0.59.37
astunparse                            1.6.3
atpublic                              5.1
attrs                                 26.1.0
audioop-lts                           0.2.2
audioread                             3.1.0
Authlib                               1.8.0
autograd                              1.9.1
babel                                 2.18.0
backcall                              0.2.0
beartype                              0.22.9
beautifulsoup4                        4.13.5
betterproto                           2.0.0b7
bigframes                             2.49.0
bigquery-magics                       0.14.0
bleach                                6.4.0
blinker                               1.9.0
blis                                  1.3.3
blobfile                              3.3.0
blosc2                                4.14.1
bokeh                                 3.8.2
Bottleneck                            1.4.2
bqplot                                0.12.47
branca                                0.8.2
brotli                                1.2.0
CacheControl                          0.14.4
cachetools                            6.2.6
catalogue                             2.0.10
certifi                               2026.7.22
cffi                                  2.1.1
chardet                               5.2.0
charset-normalizer                    3.4.9
clarabel                              0.11.1
click                                 8.5.0
cligj                                 0.7.2
cloudpathlib                          0.25.0
cloudpickle                           3.1.2
cmake                                 3.31.10
cmdstanpy                             1.3.0
colorcet                              3.2.1
colorlover                            0.3.0
community                             1.0.0b1
confection                            1.3.3
cons                                  0.4.7
contourpy                             1.4.0
cpsat-logutils                        1.0.0
cramjam                               2.13.0
cryptography                          50.0.2
cufflinks                             0.17.3
curl_cffi                             0.16.3
cvxopt                                1.3.2
cvxpy                                 1.6.7
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.13
Cython                                3.0.12
dask                                  2026.8.0
dataproc-spark-connect                1.1.0
datasets                              4.8.5
db-dtypes                             1.7.1
dbus-python                           1.3.2
debugpy                               1.8.15
decorator                             4.4.2
defusedxml                            0.7.1
deprecation                           2.1.0
diffusers                             0.40.0
dill                                  0.4.1
distributed                           2026.8.0
distro                                1.9.0
dlib                                  20.0.1
dm-tree                               0.1.10
docstring_parser                      0.18.0
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.3.2
earthengine-api                       1.7.39
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.3
einops                                0.8.2
en_core_web_sm                        3.8.0
entrypoints                           0.4
esda                                  2.9.0
et_xmlfile                            2.0.0
etils                                 1.14.0
etuples                               0.3.10
Farama-Notifications                  0.0.6
fastai                                2.8.12
fastapi                               0.141.1
fastcore                              2.2.32
fastdownload                          0.0.8
fastjsonschema                        2.22.2
fastprogress                          1.1.6
fasttransform                         0.0.5
filelock                              4.0.7
firebase-admin                        6.9.0
Flask                                 3.1.3
flatbuffers                           25.12.19
flax                                  0.11.2
folium                                0.20.0
fonttools                             4.66.1
formulaic                             1.2.2
fqdn                                  1.6.0
frozendict                            2.4.7
frozenlist                            1.8.0
fsspec                                2025.12.0
future                                1.0.0
gast                                  0.7.0
gcsfs                                 2025.12.0
GDAL                                  3.8.4
gdown                                 5.2.2
geemap                                0.38.8
geocoder                              1.38.1
geographiclib                         2.1
geopandas                             1.2.0
geopy                                 2.4.1
giddy                                 2.3.9
gin-config                            0.5.0
glob2                                 0.7
google                                3.0.0
google-adk                            2.7.1
google-api-core                       2.30.3
google-api-python-client              2.201.0
google-auth                           2.49.0
google-auth-httplib2                  0.4.3
google-auth-oauthlib                  1.5.0
google-cloud-bigquery                 3.45.2
google-cloud-bigquery-connection      1.22.0
google-cloud-bigquery-storage         2.41.0
google-cloud-core                     2.8.0
google-cloud-dataproc                 5.30.0
google-cloud-datastore                2.26.1
google-cloud-firestore                2.33.0
google-cloud-functions                1.24.0
google-cloud-language                 2.21.0
google-cloud-monitoring               2.31.0
google-cloud-resource-manager         1.18.0
google-cloud-spanner                  3.71.0
google-cloud-storage                  3.15.1
google-cloud-storage-control          1.15.0
google-cloud-translate                3.27.0
google-colab                          1.0.0
google-crc32c                         1.9.0
google-genai                          2.12.1
google-pasta                          0.2.0
google-resumable-media                2.11.0
googleapis-common-protos              1.75.5
googledrivedownloader                 1.1.0
gradio                                6.29.0
gradio_client                         2.7.1
grain                                 0.2.18
graphviz                              0.21
groovy                                0.1.2
grpc-google-iam-v1                    0.14.5
grpc-interceptor                      0.15.4
grpcio                                1.84.0
grpcio-status                         1.84.0
grpclib                               0.4.9
gspread                               6.2.1
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.1.0
gymnasium                             1.3.0
h11                                   0.16.0
h2                                    4.4.1
h5netcdf                              1.8.1
h5py                                  3.14.0
hdbscan                               0.8.44
hf-gradio                             0.4.1
hf-xet                                1.6.0
highspy                               1.15.1
holidays                              0.105
holoviews                             1.23.2
hpack                                 4.2.0
html5lib                              1.1
httpcore                              1.0.9
httpcore2                             2.13.1
httpimport                            1.4.1
httplib2                              0.32.0
httptools                             0.8.0
httpx                                 0.28.1
httpx2                                2.13.1
huggingface_hub                       1.33.0
humanize                              4.16.0
hyperframe                            6.1.0
hyperopt                              0.3.0
ibis-framework                        9.5.0
idna                                  3.20
ImageIO                               2.38.0
imageio-ffmpeg                        0.6.0
imagesize                             2.0.1
imbalanced-learn                      0.14.2
immutabledict                         4.3.1
importlib_metadata                    9.0.1
imutils                               0.5.4
inequality                            1.1.2
inflect                               7.5.0
iniconfig                             2.3.0
intel-cmplr-lib-ur                    2025.3.3
intel-openmp                          2025.3.3
interface_meta                        2.0.1
ipyevents                             2.0.4
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.20.0
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipywidgets                            7.7.1
isoduration                           20.11.0
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.1.2
jaraco.functools                      4.6.0
jax                                   0.11.1
jaxlib                                0.11.1
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.17.0
joblib                                1.6.0
joserfc                               1.7.5
jsonpatch                             1.33
jsonpickle                            4.1.2
jsonpointer                           3.1.1
jsonschema                            4.26.0
jsonschema-specifications             2025.9.1
jupyter_client                        7.4.9
jupyter-console                       6.6.3
jupyter_core                          5.9.1
jupyter-events                        0.12.1
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.20.0
jupyter_server                        2.20.0
jupyter_server_terminals              0.5.4
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.17
jupytext                              1.19.5
kaggle                                2.0.2
kagglehub                             1.0.2
kagglesdk                             0.1.37
keras                                 3.13.2
keras-hub                             0.26.0
keras-nlp                             0.26.0
keyring                               25.7.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.5.1
langchain                             1.4.3
langchain-core                        1.6.6
langchain-protocol                    0.0.19
langgraph                             1.2.12
langgraph-checkpoint                  4.2.0
langgraph-prebuilt                    1.1.0
langgraph-sdk                         0.4.5
langsmith                             0.14.2
lark                                  1.3.1
launchpadlib                          1.11.0
lazr.restfulclient                    0.14.6
lazr.uri                              1.0.6
lazy-loader                           0.6
libclang                              18.1.1
libpysal                              4.14.1
librosa                               0.11.0
lightgbm                              4.6.0
linkify-it-py                         2.2.0
llvmlite                              0.44.0
locket                                1.0.0
logical-unification                   0.4.7
lxml                                  6.1.3
lz4                                   4.4.5
Mako                                  1.3.2.dev0
mapclassify                           2.10.0
Markdown                              3.11
markdown-it-py                        4.2.0
MarkupSafe                            3.0.3
matplotlib                            3.10.0
matplotlib-inline                     0.2.2
matplotlib-venn                       1.1.2
mdit-py-plugins                       0.6.1
mdurl                                 0.1.2
mgwr                                  2.2.1
miniKanren                            1.0.5
missingno                             0.5.2
mistune                               3.3.4
mizani                                0.13.5
mkl                                   2025.3.1
ml_dtypes                             0.6.0
mlxtend                               0.23.4
mmh3                                  5.3.1
momepy                                0.11.0
more-itertools                        10.8.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.2.3
multidict                             6.9.1
multipledispatch                      1.0.0
multiprocess                          0.70.19
multitasking                          0.0.13
murmurhash                            1.0.15
music21                               9.9.2
namex                                 0.1.0
narwhals                              2.26.0
natsort                               8.4.0
nbclassic                             1.3.3
nbclient                              0.10.4
nbconvert                             7.17.1
nbformat                              5.11.1
ndindex                               1.10.1
nest-asyncio                          1.6.0
networkx                              3.7
nh3                                   0.3.7
nibabel                               5.4.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.61.2
numexpr                               2.14.2
numpy                                 2.1.3
nvidia-nccl-cu13                      2.32.3
oauth2client                          4.1.3
oauthlib                              3.3.1
omegaconf                             2.3.1
onemkl-license                        2025.3.1
openai                                2.54.0
opencv-contrib-python                 4.14.0.94
opencv-python                         5.0.0.93
opencv-python-headless                5.0.0.93
openpyxl                              3.1.5
opentelemetry-api                     1.42.1
opentelemetry-resourcedetector-gcp    1.14.0
opentelemetry-sdk                     1.42.1
opentelemetry-semantic-conventions    0.63b1
opt_einsum                            3.4.0
optax                                 0.2.8
optree                                0.20.0
orbax-checkpoint                      0.12.6
orjson                                3.12.0
orloge                                1.0.0
ormsgpack                             1.12.2
osqp                                  1.1.3
packaging                             26.3
pandas                                2.2.3
pandas-datareader                     0.11.1
pandas-gbq                            0.30.0
pandas-stubs                          2.2.3.250527
pandocfilters                         1.5.1
panel                                 1.9.4
panel-material-ui                     0.16.0
param                                 2.4.2
parso                                 0.8.7
parsy                                 2.2
partd                                 1.4.2
patsy                                 1.0.3
peewee                                4.5.2
peft                                  0.21.1
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.3.0
pip                                   24.1.2
platformdirs                          4.12.2
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.6.0
plum-dispatch                         2.9.0
pointpats                             2.5.5
polars                                1.35.2
polars-runtime-32                     1.35.2
pooch                                 1.9.0
portpicker                            1.5.2
preshed                               3.0.13
prettytable                           3.18.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.26.0
promise                               2.3
prompt_toolkit                        3.0.53
propcache                             0.5.4
prophet                               1.4.0
proto-plus                            1.29.0
protobuf                              6.33.6
psutil                                5.9.5
psycopg2                              2.9.13
psygnal                               0.16.1
ptyprocess                            0.7.0
PuLP                                  4.0.0
py-cpuinfo                            9.0.0
py4j                                  0.10.9.9
pyarrow                               23.0.1
pyasn1                                0.6.4
pyasn1_modules                        0.4.2
pycairo                               1.29.1
pycocotools                           2.0.11
pycparser                             3.0
pycryptodomex                         3.23.0
pydantic                              2.13.5
pydantic_core                         2.46.5
pydata-google-auth                    1.9.1
pydot                                 4.0.1
pydotplus                             2.0.2
PyDrive2                              1.21.1
pydub                                 0.25.1
pyerfa                                2.0.1.5
pygame                                2.6.1
pygit2                                1.20.1
Pygments                              2.21.0
PyGObject                             3.48.2
pyiceberg                             0.12.0
PyJWT                                 2.15.1
pymc                                  5.28.5
pynndescent                           0.6.0
pyogrio                               0.13.0
pyomo                                 6.10.1
PyOpenGL                              3.1.10
pyOpenSSL                             26.4.0
pyparsing                             3.3.3
pyperclip                             1.11.0
pyproj                                3.8.0
pyroaring                             1.1.0
pysal                                 25.7

In [ ]:
# 랭체인 패키지 설치
!pip install langchain

Requirement already satisfied: langchain in /usr/local/lib/python3.13/dist-packages (1.4.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.3 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.6.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.2.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain) (2.13.5)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.14.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (26.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.5)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.13/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (3.12.0)
Requirement already satisfied: websockets<17,>=14 in /usr/local/lib/python3.13/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (15.0.1)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.32.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (0.25.0)
Requirement already satisfied: httpcore2==2.13.1 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (0.10.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.5.0)

In [ ]:
# 랭체인 openai 패키지 설치
!pip install langchain-openai

Collecting langchain-openai
  Downloading langchain_openai-1.7.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: certifi>=2024.6.2 in /usr/local/lib/python3.13/dist-packages (from langchain-openai) (2026.7.22)
Collecting langchain-core<2.0.0,>=1.6.8 (from langchain-openai)
  Downloading langchain_core-1.6.9-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: openai<4.0.0,>=2.45.0 in /usr/local/lib/python3.13/dist-packages (from langchain-openai) (2.54.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from langchain-openai) (0.14.0)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.14.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (26.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (2.13.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.17.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (4.15.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (0.17.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.13/dist-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (4.67.3)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.32.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=3.5.0->openai<4.0.0,>=2.45.0->langchain-openai) (3.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.8->langchain-openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.8->langchain-openai) (3.1.1)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (2.13.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (1.0.0)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.6.8->langchain-openai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->tiktoken<1.0.0,>=0.7.0->langchain-openai) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.5.0)
Requirement already satisfied: httpcore2==2.13.1 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (2.13.1)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.8->langchain-openai) (0.10.4)
Downloading langchain_openai-1.7.0-py3-none-any.whl (145 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.6/145.6 kB 1.8 MB/s eta 0:00:00
Downloading langchain_core-1.6.9-py3-none-any.whl (572 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 573.0/573.0 kB 8.7 MB/s eta 0:00:00
Installing collected packages: langchain-core, langchain-openai
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.6.6
    Uninstalling langchain-core-1.6.6:
      Successfully uninstalled langchain-core-1.6.6
Successfully installed langchain-core-1.6.9 langchain-openai-1.7.0

In [ ]:
import os

# API Key 입력
os.environ["OPENAI_API_KEY"] = ""

순수 gpt 모델 호출
- [공식 문서](https://developers.openai.com/api/docs/guides/text?lang=python)
- [모델 종류](https://developers.openai.com/api/docs/models)

In [ ]:
# 모델 호출
from openai import OpenAI

client = OpenAI()

response = client.responses.create(
    model="gpt-6-astra",
    input="RAG가 뭔가요?",
)

print(response.output_text)

**RAG(Retrieval-Augmented Generation, 검색 증강 생성)**는 AI가 답변하기 전에 **관련 자료를 검색하고, 그 내용을 참고해 답변을 만드는 방식**입니다.

일반적인 AI가 학습한 지식만으로 답하는 것과 달리, RAG는 외부 문서나 데이터베이스에서 필요한 정보를 찾아 활용합니다. 쉽게 말해 **‘오픈북 시험을 보는 AI’**라고 생각하면 됩니다.

### 어떻게 작동하나요?
예를 들어 “우리 회사의 휴가 규정은?”이라고 질문하면:

1. **검색:** 사내 문서에서 휴가 규정과 관련된 내용을 찾습니다.
2. **전달:** 찾은 내용을 질문과 함께 AI에 제공합니다.
3. **답변 생성:** AI가 그 자료를 바탕으로 답변합니다.

### 왜 사용하나요?
- **최신 정보 활용:** 모델을 다시 학습시키지 않아도 업데이트된 문서를 참고할 수 있습니다.
- **내부 지식 활용:** 회사 규정이나 제품 매뉴얼처럼 AI가 원래 모르는 자료를 활용할 수 있습니다.
- **근거 제시:** 참고한 문서나 출처를 함께 보여줄 수 있습니다.
- **오류 감소:** 근거 없는 답변, 즉 *환각*을 줄이는 데 도움이 됩니다.

다만, **검색한 자료가 부정확하거나 필요한 내용을 찾지 못하면 답변도 틀릴 수 있습니다.** RAG가 정확성을 완전히 보장하는 것은 아닙니다.

## Model

### Model I/O

In [ ]:
# 모델 객체 생성
from langchain.chat_models import init_chat_model

model = init_chat_model("gpt-5.4-mini")

In [ ]:
# 응답 출력
response = model.invoke("RAG가 뭔가요?")

In [ ]:
# content
response.content

'RAG는 **Retrieval-Augmented Generation**의 약자로,  \n한국어로는 보통 **검색 증강 생성**이라고 합니다.\n\n간단히 말하면:\n\n- **검색(Retrieval)**: 관련 자료를 먼저 찾아오고\n- **생성(Generation)**: 그 자료를 바탕으로 답변을 만드는 방식입니다.\n\n### 왜 쓰나요?\nLLM은 학습된 지식만으로 답하므로,\n- 최신 정보에 약할 수 있고\n- 회사 내부 문서처럼 모델이 원래 모르는 정보는 답하기 어렵습니다.\n\nRAG는 이런 문제를 줄이기 위해,\n질문이 들어오면 먼저 **문서, DB, 위키, PDF** 같은 외부 자료를 찾아서\n그 내용을 참고해 답합니다.\n\n### 예시\n사용자 질문:  \n“우리 회사 휴가 규정이 어떻게 되나요?”\n\nRAG 방식:\n1. 사내 규정 문서에서 휴가 관련 내용을 검색\n2. 찾은 내용을 LLM에 넣음\n3. LLM이 그 내용을 바탕으로 자연스럽게 답변\n\n### 장점\n- 최신 정보 반영 가능\n- 내부 문서 기반 답변 가능\n- 환각(hallucination) 줄이는 데 도움\n\n### 한계\n- 검색 품질이 낮으면 답도 나빠짐\n- 문서 정리/색인/권한 관리가 필요함\n- 시스템이 조금 더 복잡해짐\n\n원하시면 제가  \n**“RAG와 일반 LLM의 차이”** 또는 **“RAG를 어떻게 구현하는지”**도 쉽게 설명해드릴게요.'

In [ ]:
# usage_metadata
response.usage_metadata

{'input_tokens': 14,
 'output_tokens': 349,
 'total_tokens': 363,
 'input_token_details': {'audio': 0, 'cache_read': 0},
 'output_token_details': {'audio': 0, 'reasoning': 0}}

#### Model I/O 실습
**GPT-5.5 모델에게 'cancer immunotherapy'가 뭔지 질문하고, 몇 토큰을 총 사용했는지 출력하시오.**

In [ ]:
# 모델 객체 생성
from langchain.chat_models import init_chat_model

model = init_chat_model("gpt-5.5")

response = model.invoke("cancer immunotherapy 가 뭔가요?")

In [ ]:
response.content

'**암 면역치료(cancer immunotherapy)**는 우리 몸의 **면역체계가 암세포를 더 잘 찾아내고 공격하도록 돕는 치료법**입니다. 기존의 항암화학요법이 빠르게 분열하는 세포를 직접 공격하는 방식이라면, 면역치료는 **면역세포의 힘을 이용하거나 강화**한다는 점이 다릅니다.\n\n대표적인 종류는 다음과 같습니다.\n\n1. **면역관문억제제**\n   - 암세포가 면역세포의 공격을 피하기 위해 사용하는 “브레이크”를 풀어주는 약입니다.\n   - 예: PD-1, PD-L1, CTLA-4 억제제\n   - 흑색종, 폐암, 신장암, 방광암 등 여러 암에서 사용됩니다.\n\n2. **CAR-T 세포치료**\n   - 환자의 T세포를 꺼내 암세포를 잘 인식하도록 유전자 조작한 뒤 다시 주입하는 치료입니다.\n   - 일부 혈액암에서 효과가 큽니다.\n\n3. **암 백신**\n   - 암세포의 특정 항원을 면역계에 알려 암을 공격하게 하는 방식입니다.\n   - 예방 백신과 치료 백신이 있습니다. 예를 들어 HPV 백신은 자궁경부암 예방에 도움이 됩니다.\n\n4. **사이토카인 치료**\n   - 인터루킨, 인터페론 같은 면역 신호물질을 이용해 면역반응을 높입니다.\n\n5. **단클론항체 치료**\n   - 암세포의 특정 표적에 달라붙어 면역계가 암세포를 공격하도록 돕거나 암 성장 신호를 차단합니다.\n\n장점은 일부 환자에서 **오래 지속되는 효과**가 나타날 수 있다는 점입니다. 하지만 모든 암이나 모든 환자에게 효과가 있는 것은 아니며, 면역계가 과도하게 활성화되면서 **피부발진, 장염, 간염, 폐렴, 갑상선 이상** 같은 면역 관련 부작용이 생길 수 있습니다.\n\n즉, 암 면역치료는 **면역체계를 활용해 암을 치료하는 최신 치료 전략**이며, 암의 종류·유전자 특성·환자의 상태에 따라 적용 여부가 결정됩니다.'

In [ ]:
# content 출력

In [ ]:
# usage_metadata 출력
response.usage_metadata

{'input_tokens': 16,
 'output_tokens': 539,
 'total_tokens': 555,
 'input_token_details': {'audio': 0, 'cache_read': 0},
 'output_token_details': {'audio': 0, 'reasoning': 25}}

### parameter

In [ ]:
# parameter 설정 1
model = init_chat_model(
    "gpt-5.4-mini",
    temperature = 0
)

In [ ]:
# 실행
response = model.invoke("앵무새의 털 색상이 화려한 이유는 뭔가요?")

In [ ]:
# content 출력
response.content

'앵무새의 털 색상이 화려한 이유는 **여러 가지 생물학적 이유가 겹친 결과**입니다. 핵심은 다음과 같아요.\n\n1. **짝짓기와 신호 전달**\n   - 화려한 깃털은 건강하고 잘 자라는 개체라는 신호가 될 수 있어요.\n   - 그래서 상대를 유혹하거나, 종(種) 안에서 서로를 구분하는 데 도움이 됩니다.\n\n2. **종 구분**\n   - 앵무새는 비슷한 지역에 여러 종이 살 수 있어서, 깃털 색이 종을 알아보는 표지 역할을 합니다.\n   - 서로 다른 종끼리 짝짓는 것을 줄여 주기도 해요.\n\n3. **위장과 환경 적응**\n   - 일부 색은 주변 환경과 어울려 포식자로부터 몸을 숨기는 데 도움을 줍니다.\n   - 다만 앵무새는 전반적으로 화려한 편이라, 위장보다 다른 기능이 더 중요하게 작용한 경우가 많습니다.\n\n4. **깃털 구조와 색소**\n   - 앵무새의 색은 단순히 색소만이 아니라, 깃털의 미세한 구조와 색소의 조합으로 만들어집니다.\n   - 특히 앵무새는 **psittacofulvin**이라는 특별한 색소를 가지고 있어 붉은색, 노란색, 주황색 계열을 내는 데 기여합니다.\n   - 파란색은 색소보다도 깃털 구조가 빛을 산란시켜 만들어지는 경우가 많습니다.\n\n한마디로 말하면, **앵무새의 화려한 색은 짝짓기, 종 구분, 생존에 유리한 신호 기능과 깃털의 생화학적·구조적 특성이 합쳐진 결과**입니다.\n\n원하시면 제가 **“왜 파란색 앵무새는 파랗게 보이는지”**도 더 쉽게 설명해 드릴게요.'

In [ ]:
# temperature 설정
model = init_chat_model(
    "gpt-5.4-mini",
    temperature = 0.7
)

In [ ]:
# 실행
response = model.invoke("앵무새의 털 색상이 화려한 이유는 뭔가요?")

In [ ]:
# content 출력
response.content

'앵무새의 털색이 화려한 이유는 크게 **의사소통**, **짝짓기**, **종(種) 인식**, 그리고 **몸 상태를 드러내는 신호**와 관련이 있습니다.\n\n### 1) 서로를 알아보고 소통하기 위해\n앵무새는 무리 생활을 많이 하는 새라서, 화려한 색이 **같은 종이나 개체를 구분하는 표식** 역할을 합니다.  \n특히 숲처럼 시야가 제한된 환경에서는 색이 중요한 신호가 될 수 있어요.\n\n### 2) 짝을 유인하기 위해\n많은 새들처럼 앵무새도 **번식 상대를 고를 때 색이 중요한 단서**가 됩니다.  \n선명한 깃털은 보통 **건강하고 영양 상태가 좋은 개체**라는 신호로 해석되기 쉬워서, 이성에게 더 매력적으로 보일 수 있습니다.\n\n### 3) 생존과 은폐에도 나름 도움이 되기 위해\n화려한 색이 꼭 눈에 잘 띄기만 하는 건 아닙니다.  \n앵무새가 주로 사는 **열대 지역의 나무와 꽃, 과일** 같은 환경에서는 색이 오히려 주변과 잘 어울려 **위장 효과**를 내기도 합니다.\n\n### 4) 깃털 색을 만드는 방식\n앵무새의 색은 단순히 “색소”만으로 생기는 게 아니라,\n- **멜라닌**: 검정, 갈색 계열\n- **카로티노이드**: 빨강, 주황, 노랑 계열\n- 그리고 앵무새 특유의 **깃털 구조**  \n가 조합되어 매우 선명하고 다양한 색을 만듭니다.\n\n특히 앵무새는 다른 새들과 달리 **특수한 깃털 구조와 색소 체계** 덕분에 초록, 빨강, 파랑이 아주 뚜렷하게 나타나는 경우가 많습니다.\n\n원하시면 제가 이어서 **“앵무새는 왜 초록색이 많은가?”** 또는 **“새의 깃털 색은 어떻게 만들어지나?”**도 쉽게 설명해드릴게요.'

In [ ]:
# reasoning 설정 1
model = init_chat_model(
    "gpt-5.4-mini",
    reasoning = {
        "effort" : "low"
    }
)

In [ ]:
# 실행
response = model.invoke('오늘 서울 날씨 어때?')

In [ ]:
# response 출력
response.usage_metadata

{'input_tokens': 13,
 'output_tokens': 237,
 'total_tokens': 250,
 'input_token_details': {'cache_creation': 0, 'cache_read': 0},
 'output_token_details': {'reasoning': 105}}

In [ ]:
# 답변 출력 (response.text)
response.text

'죄송하지만 저는 **실시간 날씨 정보에는 직접 접근할 수 없어요.**  \n그래서 오늘 **서울 날씨를 지금 바로 정확히** 알려드리진 못합니다.\n\n대신 빠르게 확인하려면:\n- **네이버 날씨**\n- **구글에 “서울 날씨”**\n- **기상청 날씨누리**\n\n원하시면 제가 대신\n1. **오늘 서울 날씨 확인하는 가장 빠른 방법**을 알려드리거나  \n2. **시간대별로 뭘 입으면 좋을지** 기준을 알려드릴게요.'

In [ ]:
# reasoning 설정 2
model = init_chat_model(
    "gpt-5.4-mini",
    reasoning = {
        "effort" : "high"
    }
)

In [ ]:
# 실행
response = model.invoke('오늘 서울 날씨 어때?')

In [ ]:
# response 출력
response.usage_metadata

{'input_tokens': 13,
 'output_tokens': 313,
 'total_tokens': 326,
 'input_token_details': {'cache_creation': 0, 'cache_read': 0},
 'output_token_details': {'reasoning': 192}}

In [ ]:
# 답변 출력
response.text

'실시간 서울 날씨는 제가 바로 조회할 수는 없어요.  \n대신 **기상청**, **네이버 날씨**, **카카오날씨**에서 **“서울”** 검색하면 오늘 기온/강수/미세먼지까지 바로 볼 수 있어요.\n\n원하시면 제가  \n- **오늘 입을 옷 추천**\n- **비 올 때 대비**\n- **현재 예보 해석**  \n\n도 도와드릴게요. 예보 화면을 보내주시면 바로 읽어드릴 수 있어요.'

In [ ]:
# reasoning 설정 3
model = init_chat_model(
    "gpt-5.4-mini",
    reasoning = {
        "effort" : "none"
    }
)

In [ ]:
# 실행
response = model.invoke('오늘 서울 날씨 어때?')

In [ ]:
# response 출력
response.usage_metadata

{'input_tokens': 13,
 'output_tokens': 110,
 'total_tokens': 123,
 'input_token_details': {'cache_creation': 0, 'cache_read': 0},
 'output_token_details': {'reasoning': 0}}

In [ ]:
# 답변 출력
response.text

'죄송하지만 저는 현재 실시간 날씨를 직접 조회할 수는 없어요.  \n원하시면 제가 **서울 날씨를 확인하는 가장 빠른 방법**을 알려드릴게요.\n\n예를 들면:\n- **기상청** 앱/웹\n- **네이버 날씨**\n- **구글에서 “서울 날씨” 검색**\n\n원하시면 제가 바로 **오늘 서울 날씨를 확인할 수 있는 링크/방법**을 간단히 안내해드릴게요.'

### 주요 메서드

#### stream()

In [ ]:
model = init_chat_model("gpt-5.4-mini")

In [ ]:
# stream()
for chunk in model.stream("RAG가 뭔지 1000자 이상 3000자 이하로 답변하시오."):
  print(chunk.text , end="")

RAG는 **Retrieval-Augmented Generation**의 약자로, 한국어로는 보통 **검색 증강 생성**이라고 번역합니다. 쉽게 말해, AI가 답변을 만들기 전에 **관련 정보를 먼저 찾아보고** 그 내용을 바탕으로 **더 정확한 답을 생성하는 방식**입니다. 일반적인 생성형 AI는 학습된 데이터만을 바탕으로 답을 만들기 때문에, 최신 정보나 특정 문서 안의 세부 내용을 정확히 반영하지 못할 수 있습니다. 반면 RAG는 외부 데이터베이스, 문서 저장소, 웹 문서, 사내 위키 같은 곳에서 필요한 정보를 검색한 뒤 그 결과를 참고하여 답변을 생성합니다.

RAG의 핵심은 두 단계입니다. 첫째는 **retrieval(검색)** 단계입니다. 사용자의 질문이 들어오면 시스템은 질문과 관련성이 높은 문서 조각, 문장, 표, FAQ 등을 찾아냅니다. 이때 단순 키워드 검색만 하는 것이 아니라, 임베딩 벡터를 활용한 의미 기반 검색을 통해 질문의 의도와 유사한 내용을 찾는 경우가 많습니다. 둘째는 **generation(생성)** 단계입니다. 검색된 자료를 프롬프트에 함께 넣어 언어 모델이 그 자료를 근거로 답변을 작성합니다. 즉, 모델이 혼자 “기억”해서 답하는 것이 아니라, “찾아온 자료를 읽고 답하는” 구조입니다.

RAG가 주목받는 이유는 여러 가지입니다. 가장 큰 장점은 **정확성 향상**입니다. 모델이 모르는 내용을 억지로 추측하는 환각(hallucination) 현상을 줄일 수 있습니다. 또한 **최신성**을 확보하기 좋습니다. 언어 모델 자체를 다시 학습시키지 않아도, 검색 대상 문서만 갱신하면 새로운 정보에 대응할 수 있습니다. 더불어 **도메인 특화**에도 강합니다. 예를 들어 의료, 법률, 금융, 고객지원처럼 전문 문서가 많은 분야에서는 RAG를 활용해 내부 지식베이스를 바탕으로 답변하게 할 수 있습니다.

예를 들어 회사의 사내 규정에 대해 직원이 질문했다고 합시다. 일반 AI는 그 회사의 최신 규정을 알지 못할 수 있지만, RAG 시스템은 사내 규정 문서를 검색해 해당 조항을 찾고 이를 근거로 답변할 수 있습니다. “연차는 몇 일인가요?”, “비용 정산 절차는 어떻게 되나요?” 같은 질문에 문서 근거를 포함한 답을 제공하는 식입니다.

다만 RAG가 만능은 아닙니다. 검색 품질이 낮으면 잘못된 문서를 가져와서 답변도 부정확해질 수 있습니다. 또한 문서를 잘게 나누는 방식, 검색 순위, 프롬프트 구성에 따라 성능이 크게 달라집니다. 따라서 RAG를 잘 만들려면 문서 전처리, 인덱싱, 검색 알고리즘, 재정렬(reranking), 출처 표시 같은 요소를 함께 고려해야 합니다.

정리하면, RAG는 **“필요한 정보를 찾아온 뒤 그 정보를 바탕으로 답을 만드는 AI 방식”**입니다. 단순히 말을 잘하는 AI를 넘어서, 실제 문서와 지식을 활용해 더 신뢰할 수 있는 답변을 제공하려는 접근이라고 볼 수 있습니다.

#### batch()

In [ ]:
inputs = [
    "과적합이 뭔가요?",
    "앵무새의 털 색상이 화려한 이유는?",
    "AI Agent 기반 서비스는 뭐가 있나요?"
]

In [ ]:
# batch
responses = model.batch(inputs)

In [ ]:
# 응답 출력
responses

[AIMessage(content='과적합(Overfitting)은 **학습 데이터에는 너무 잘 맞지만, 새로운 데이터에는 성능이 떨어지는 현상**입니다.\n\n예를 들어, 시험 문제를 외워서 풀었는데 **비슷한 새 문제는 잘 못 푸는 상태**라고 생각하면 됩니다.\n\n### 쉽게 말하면\n- **훈련 데이터 성능은 매우 좋음**\n- **테스트/실전 데이터 성능은 나쁨**\n- 데이터의 **진짜 규칙**보다 **우연한 잡음이나 세부 패턴**까지 외워버린 경우입니다.\n\n### 왜 생기나요?\n- 모델이 너무 복잡할 때\n- 데이터가 너무 적을 때\n- 잡음이 많은 데이터를 학습할 때\n\n### 예시\n개가 있는 사진을 구분하는 모델이:\n- 훈련 사진에만 있는 배경색\n- 특정 카메라 화질\n- 우연히 같이 등장한 물체  \n같은 것까지 학습해버리면, 새 사진에서는 잘 못 맞힐 수 있습니다.\n\n### 해결 방법\n- 더 많은 데이터 사용\n- 모델 단순화\n- 정규화(Regularization)\n- 드롭아웃(Dropout)\n- 조기 종료(Early stopping)\n\n원하시면 **과적합, 과소적합, 일반화**를 같이 비교해서도 설명해드릴게요.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 298, 'prompt_tokens': 15, 'total_tokens': 313, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXLiip8wMbl06XcHv2chhnevDYcky', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a124b2-401f-7be2-83ba-f16caccb74a6-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 15, 'output_tokens': 298, 'total_tokens': 313, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
 AIMessage(content='앵무새의 털 색이 화려한 이유는 여러 가지가 있습니다.\n\n1. **짝짓기 신호**\n   - 화려한 색은 건강하고 좋은 유전자를 가진 개체라는 신호가 될 수 있어요.\n   - 특히 번식기에 다른 개체에게 자신을 어필하는 데 도움이 됩니다.\n\n2. **종 구분**\n   - 비슷한 지역에 사는 여러 앵무새 종들이 서로를 구분하기 쉽도록 진화했을 수 있습니다.\n\n3. **의사소통**\n   - 깃털 색은 감정 상태나 경고, 위협 같은 신호를 전달하는 데도 쓰입니다.\n\n4. **먹이와 환경의 영향**\n   - 앵무새는 주로 과일, 씨앗, 꽃가루 같은 다양한 먹이를 먹는데, 이런 환경과 생활 방식 속에서 다양한 색이 발달한 것으로 볼 수 있습니다.\n\n5. **진화적 이점**\n   - 화려한 깃털이 꼭 불리하기만 한 것은 아니고, 숲처럼 색이 다양한 환경에서는 오히려 위장이나 시각적 신호로 유리할 수 있습니다.\n\n한마디로, **앵무새의 화려한 털 색은 번식, 소통, 종 인식, 환경 적응이 복합적으로 작용한 결과**라고 볼 수 있습니다.\n\n원하시면 제가 **“왜 다른 새보다 특히 앵무새가 더 화려한지”**도 이어서 설명해드릴게요.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 333, 'prompt_tokens': 21, 'total_tokens': 354, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXLiiNiZpAaqVO1M57VvPDDHjnm6z', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a124b2-4021-7dc0-b0d0-8eb714af83b2-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 21, 'output_tokens': 333, 'total_tokens': 354, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
 AIMessage(content='AI Agent 기반 서비스는 “사용자의 목표를 이해하고, 여러 단계를 스스로 계획·실행하는” 형태의 서비스입니다. 단순 챗봇보다 **업무 수행 능력**이 더 강한 것이 특징이에요.\n\n대표적인 예시는 아래와 같습니다.\n\n### 1) 개인 비서형\n- **일정 관리 에이전트**: 회의 잡기, 일정 조율, 알림 설정\n- **이메일 에이전트**: 메일 분류, 답장 초안 작성, 후속 메일 발송\n- **여행 플래너 에이전트**: 항공권/숙소/일정 추천 및 예약 보조\n\n### 2) 업무 자동화형\n- **문서 작성 에이전트**: 보고서, 제안서, 회의록 작성\n- **리서치 에이전트**: 웹 검색, 자료 요약, 경쟁사 분석\n- **영업/마케팅 에이전트**: 리드 발굴, 고객 응대, 캠페인 초안 생성\n\n### 3) 개발/IT형\n- **코딩 에이전트**: 코드 생성, 버그 수정, 테스트 작성\n- **DevOps 에이전트**: 로그 분석, 장애 대응 안내, 배포 체크리스트 자동화\n- **데이터 분석 에이전트**: SQL 작성, 데이터 요약, 대시보드 인사이트 생성\n\n### 4) 고객지원형\n- **상담 에이전트**: FAQ 응답, 환불/교환 안내\n- **예약 에이전트**: 예약 변경/취소 처리\n- **콜센터 보조 에이전트**: 상담원 응답 추천, 이력 요약\n\n### 5) 산업 특화형\n- **법률 에이전트**: 계약서 검토, 조항 비교\n- **의료 에이전트**: 증상 안내, 진료 예약 보조\n- **금융 에이전트**: 지출 분석, 투자 리포트 요약\n- **교육 에이전트**: 개인 맞춤 학습, 문제풀이 코치\n\n### 6) 멀티에이전트형\n- 여러 에이전트가 역할 분담:\n  - 리서치 에이전트\n  - 요약 에이전트\n  - 실행 에이전트\n  - 검증 에이전트  \n- 예: “시장 조사 → 경쟁사 분석 → 보고서 작성 → 검수”를 자동으로 진행\n\n---\n\n## 현재 많이 알려진 서비스 예\n- **ChatGPT / Claude / Gemini**: 에이전트 기능을 점점 강화\n- **Microsoft Copilot**: 업무 자동화 중심\n- **Perplexity**: 검색·리서치 에이전트 성격\n- **LangChain / AutoGen / CrewAI**: 에이전트 구축 프레임워크\n- **Zapier AI / n8n + AI**: 업무 자동화 에이전트 구성\n\n---\n\n## 핵심 차이\n- **챗봇**: 질문에 답변\n- **AI Agent**: 목표를 받고 여러 도구를 써서 실제 작업 수행\n\n예:\n- 챗봇: “회의 일정 잡는 방법 알려줘”\n- 에이전트: “다음 주 팀 회의 잡아줘” → 참가자 확인 → 시간 조율 → 캘린더 등록 → 메일 발송\n\n원하시면 제가 다음 중 하나로 이어서 정리해드릴 수 있어요:\n1. **국내/해외 AI Agent 서비스 사례**\n2. **산업별 AI Agent 서비스 아이디어**\n3. **AI Agent를 만들기 위한 기술 구성도**\n4. **AI Agent 서비스 기획서 예시**', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 823, 'prompt_tokens': 16, 'total_tokens': 839, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXLiiJtJRWwAZtDvwXpZG7WWEtFE8', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a124b2-4024-7c52-b3da-511f74cb394e-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 16, 'output_tokens': 823, 'total_tokens': 839, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]

In [ ]:
for response in responses:
    print(response.content)

과적합(Overfitting)은 **학습 데이터에는 너무 잘 맞지만, 새로운 데이터에는 성능이 떨어지는 현상**입니다.

예를 들어, 시험 문제를 외워서 풀었는데 **비슷한 새 문제는 잘 못 푸는 상태**라고 생각하면 됩니다.

### 쉽게 말하면
- **훈련 데이터 성능은 매우 좋음**
- **테스트/실전 데이터 성능은 나쁨**
- 데이터의 **진짜 규칙**보다 **우연한 잡음이나 세부 패턴**까지 외워버린 경우입니다.

### 왜 생기나요?
- 모델이 너무 복잡할 때
- 데이터가 너무 적을 때
- 잡음이 많은 데이터를 학습할 때

### 예시
개가 있는 사진을 구분하는 모델이:
- 훈련 사진에만 있는 배경색
- 특정 카메라 화질
- 우연히 같이 등장한 물체
같은 것까지 학습해버리면, 새 사진에서는 잘 못 맞힐 수 있습니다.

### 해결 방법
- 더 많은 데이터 사용
- 모델 단순화
- 정규화(Regularization)
- 드롭아웃(Dropout)
- 조기 종료(Early stopping)

원하시면 **과적합, 과소적합, 일반화**를 같이 비교해서도 설명해드릴게요.
앵무새의 털 색이 화려한 이유는 여러 가지가 있습니다.

1. **짝짓기 신호**
   - 화려한 색은 건강하고 좋은 유전자를 가진 개체라는 신호가 될 수 있어요.
   - 특히 번식기에 다른 개체에게 자신을 어필하는 데 도움이 됩니다.

2. **종 구분**
   - 비슷한 지역에 사는 여러 앵무새 종들이 서로를 구분하기 쉽도록 진화했을 수 있습니다.

3. **의사소통**
   - 깃털 색은 감정 상태나 경고, 위협 같은 신호를 전달하는 데도 쓰입니다.

4. **먹이와 환경의 영향**
   - 앵무새는 주로 과일, 씨앗, 꽃가루 같은 다양한 먹이를 먹는데, 이런 환경과 생활 방식 속에서 다양한 색이 발달한 것으로 볼 수 있습니다.

5. **진화적 이점**
   - 화려한 깃털이 꼭 불리하기만 한 것은 아니고, 숲처럼 색이 다양한 환경에서는 오히려 위장이나 시각적 신호로 유리할 수 있습니다.

한마디로, **앵무새의 화려한 털 색은 번식, 소통, 종 인식, 환경 적응이 복합적으로 작용한 결과**라고 볼 수 있습니다.

원하시면 제가 **“왜 다른 새보다 특히 앵무새가 더 화려한지”**도 이어서 설명해드릴게요.
AI Agent 기반 서비스는 “사용자의 목표를 이해하고, 여러 단계를 스스로 계획·실행하는” 형태의 서비스입니다. 단순 챗봇보다 **업무 수행 능력**이 더 강한 것이 특징이에요.

대표적인 예시는 아래와 같습니다.

### 1) 개인 비서형
- **일정 관리 에이전트**: 회의 잡기, 일정 조율, 알림 설정
- **이메일 에이전트**: 메일 분류, 답장 초안 작성, 후속 메일 발송
- **여행 플래너 에이전트**: 항공권/숙소/일정 추천 및 예약 보조

### 2) 업무 자동화형
- **문서 작성 에이전트**: 보고서, 제안서, 회의록 작성
- **리서치 에이전트**: 웹 검색, 자료 요약, 경쟁사 분석
- **영업/마케팅 에이전트**: 리드 발굴, 고객 응대, 캠페인 초안 생성

### 3) 개발/IT형
- **코딩 에이전트**: 코드 생성, 버그 수정, 테스트 작성
- **DevOps 에이전트**: 로그 분석, 장애 대응 안내, 배포 체크리스트 자동화
- **데이터 분석 에이전트**: SQL 작성, 데이터 요약, 대시보드 인사이트 생성

### 4) 고객지원형
- **상담 에이전트**: FAQ 응답, 환불/교환 안내
- **예약 에이전트**: 예약 변경/취소 처리
- **콜센터 보조 에이전트**: 상담원 응답 추천, 이력 요약

### 5) 산업 특화형
- **법률 에이전트**: 계약서 검토, 조항 비교
- **의료 에이전트**: 증상 안내, 진료 예약 보조
- **금융 에이전트**: 지출 분석, 투자 리포트 요약
- **교육 에이전트**: 개인 맞춤 학습, 문제풀이 코치

### 6) 멀티에이전트형
- 여러 에이전트가 역할 분담:
  - 리서치 에이전트
  - 요약 에이전트
  - 실행 에이전트
  - 검증 에이전트
- 예: “시장 조사 → 경쟁사 분석 → 보고서 작성 → 검수”를 자동으로 진행

---

## 현재 많이 알려진 서비스 예
- **ChatGPT / Claude / Gemini**: 에이전트 기능을 점점 강화
- **Microsoft Copilot**: 업무 자동화 중심
- **Perplexity**: 검색·리서치 에이전트 성격
- **LangChain / AutoGen / CrewAI**: 에이전트 구축 프레임워크
- **Zapier AI / n8n + AI**: 업무 자동화 에이전트 구성

---

## 핵심 차이
- **챗봇**: 질문에 답변
- **AI Agent**: 목표를 받고 여러 도구를 써서 실제 작업 수행

예:
- 챗봇: “회의 일정 잡는 방법 알려줘”
- 에이전트: “다음 주 팀 회의 잡아줘” → 참가자 확인 → 시간 조율 → 캘린더 등록 → 메일 발송

원하시면 제가 다음 중 하나로 이어서 정리해드릴 수 있어요:
1. **국내/해외 AI Agent 서비스 사례**
2. **산업별 AI Agent 서비스 아이디어**
3. **AI Agent를 만들기 위한 기술 구성도**
4. **AI Agent 서비스 기획서 예시**

### Model 실습
**GPT-5.5** 모델에게 **추론을 중간**으로 설정해 'RAG 성능 향상을 위한 검토 사항' 답변을 받아보자 (**stream하게**)

In [ ]:
model = init_chat_model(
    "gpt-5.5",
    reasoning = {
        "effort" : "medium"
    }
  )

In [ ]:
for chunk in model.stream("RAG 성능 향상을 위한 검토 사항") :
    print(chunk.text, end = "")

아래는 **RAG(Retrieval-Augmented Generation) 성능 향상을 위해 점검해야 할 주요 검토 사항**입니다.

---

## 1. 데이터 품질 검토

RAG 성능은 결국 검색 대상 문서의 품질에 크게 좌우됩니다.

### 확인할 사항
- 문서가 최신 상태인가?
- 중복 문서가 많은가?
- 잘못된 정보, 오래된 정책, 폐기된 문서가 포함되어 있는가?
- 표, 이미지, PDF, HTML 등이 제대로 파싱되었는가?
- 문서별 출처, 작성일, 버전, 권한 정보가 보존되어 있는가?

### 개선 방향
- 중복 제거
- 오래된 문서 아카이빙
- 문서 메타데이터 정비
- 파싱 오류 검수
- 업무 기준으로 문서 카테고리 재정리

---

## 2. Chunking 전략

문서를 어떻게 나누느냐에 따라 검색 품질이 크게 달라집니다.

### 검토 포인트
- Chunk 크기가 너무 작아 맥락이 부족하지 않은가?
- Chunk 크기가 너무 커서 불필요한 정보가 많이 포함되지 않는가?
- 문단, 제목, 표, 조항 단위가 유지되는가?
- Overlap이 적절한가?
- 제목, 섹션 정보가 Chunk에 포함되어 있는가?

### 일반적인 기준
- FAQ / 짧은 문서: 작은 Chunk
- 정책 / 매뉴얼: 섹션 단위 Chunk
- 코드 / 기술 문서: 함수, 클래스, API 단위 Chunk
- 법률 / 계약서: 조항 단위 Chunk

### 개선 방향
- 단순 길이 기반 분할보다 **의미 기반 분할** 고려
- Chunk에 상위 제목을 함께 포함
- 10~20% 수준의 overlap 테스트
- 문서 유형별로 다른 chunking 전략 적용

---

## 3. Embedding 모델 검토

Embedding 모델은 질문과 문서의 의미적 유사도를 계산하는 핵심 요소입니다.

### 확인할 사항
- 한국어 성능이 충분한 모델인가?
- 도메인 용어를 잘 반영하는가?
- 다국어 문서가 있다면 multilingual embedding이 필요한가?
- 질문과 문서의 표현 방식 차이를 잘 연결하는가?

### 개선 방향
- 한국어 특화 또는 다국어 embedding 모델 비교
- 사내 용어, 제품명, 약어에 대한 성능 테스트
- 필요 시 domain fine-tuning 검토
- embedding 차원 수와 검색 속도 간 균형 확인

---

## 4. 검색 방식 개선

기본 벡터 검색만으로는 충분하지 않은 경우가 많습니다.

### 검색 방식
| 방식 | 설명 |
|---|---|
| Vector Search | 의미 기반 검색 |
| Keyword Search | 키워드, 정확한 용어 검색 |
| Hybrid Search | Vector + Keyword 조합 |
| Metadata Filtering | 부서, 날짜, 문서유형 등 조건 검색 |
| Reranking | 1차 검색 결과를 재정렬 |

### 개선 방향
- **Hybrid Search** 도입 검토
- BM25 + Vector Search 조합
- 문서 유형, 날짜, 권한 기준 필터링
- 검색 결과 상위 K 값 조정
- 검색 후 reranker 적용

---

## 5. Reranker 적용

Embedding 검색 결과는 대략적인 후보군을 찾는 데 유리하지만, 최종 순위가 항상 정확하지는 않습니다.

### Reranker의 역할
- 질문과 후보 문서 간 관련성을 다시 평가
- 검색 결과 순위 개선
- 불필요한 chunk 제거

### 적용 방식
1. Vector DB에서 top 20~50개 검색
2. Reranker로 재정렬
3. 상위 3~10개만 LLM에 전달

### 기대 효과
- 정답 포함률 개선
- hallucination 감소
- 불필요한 context 축소

---

## 6. Query 개선

사용자의 질문 자체가 모호하거나 짧으면 검색 성능이 떨어질 수 있습니다.

### 검토 포인트
- 질문이 너무 짧거나 모호하지 않은가?
- 약어, 오타, 사내 용어가 포함되어 있는가?
- 질문에 필요한 조건이 빠져 있지 않은가?

### 개선 기법
- Query rewriting
- Query expansion
- HyDE 방식
- Multi-query retrieval
- 사용자 질문 의도 분류

### 예시
사용자 질문:

> “휴가 기준 알려줘”

개선된 검색 질의:

> “직원의 연차휴가 발생 기준, 사용 조건, 이월 가능 여부에 대한 사내 규정”

---

## 7. Context 구성 방식

검색된 문서를 LLM에 어떻게 전달하는지도 중요합니다.

### 확인할 사항
- 너무 많은 chunk를 넣어 noise가 많지 않은가?
- 중요한 chunk가 뒤쪽에 배치되어 무시되지 않는가?
- 출처 정보가 함께 전달되는가?
- 중복된 context가 많지 않은가?

### 개선 방향
- 관련도 높은 순서로 context 정렬
- 중복 chunk 제거
- 문서 제목, 섹션, 날짜 포함
- 답변에 필요한 최소한의 context만 전달
- 긴 context 사용 시 구조화된 형식으로 제공

---

## 8. Prompt 설계

RAG에서는 prompt가 답변 품질과 hallucination 방지에 큰 영향을 줍니다.

### 포함하면 좋은 지시사항
- 제공된 문서 근거만 사용하라
- 문서에 없으면 모른다고 답하라
- 출처를 표시하라
- 불확실한 내용은 추측하지 말라
- 여러 문서가 충돌하면 최신 문서를 우선하라

### 예시 Prompt 방향

```text
아래 제공된 참고 문서만 기반으로 답변하세요.
문서에 없는 내용은 추측하지 말고 "제공된 문서에서 확인할 수 없습니다"라고 답하세요.
답변에는 관련 문서 제목 또는 출처를 포함하세요.
```

---

## 9. 답변 생성 품질

검색은 잘 되었는데 답변이 부정확한 경우도 많습니다.

### 검토 포인트
- 검색된 근거를 제대로 반영하는가?
- 문서 내용을 과도하게 요약하면서 핵심 조건을 누락하지 않는가?
- 수치, 날짜, 조건을 정확히 전달하는가?
- 서로 다른 문서의 내용을 섞어 잘못된 결론을 내리지 않는가?

### 개선 방향
- 답변 형식 지정
- 근거 문장 인용
- step-by-step 답변 요구
- 출처별 요약 후 최종 답변 생성
- 긴 문서의 경우 map-reduce 방식 사용

---

## 10. 평가 지표 설계

RAG 성능 개선은 반드시 평가셋을 기반으로 해야 합니다.

### 검색 평가 지표
- Recall@K
- Precision@K
- MRR
- nDCG
- Hit Rate
- 정답 문서 포함률

### 생성 평가 지표
- Faithfulness
- Answer Relevance
- Context Relevance
- Hallucination Rate
- 출처 정확도
- 사용자 만족도

### 운영 평가 지표
- 응답 속도
- 비용
- 실패율
- 검색 실패율
- 재질문 비율
- 사용자의 thumbs up/down 비율

---

## 11. Golden Dataset 구축

성능 개선을 위해 대표 질문과 정답 세트가 필요합니다.

### 포함할 항목
- 사용자 질문
- 기대 답변
- 정답 문서 / chunk
- 허용 가능한 표현
- 금지해야 할 답변
- 난이도
- 도메인 카테고리

### 예시

| 질문 | 기대 답변 | 정답 문서 |
|---|---|---|
| 연차는 언제 발생하나요? | 입사 후 1년 미만은 월 1일, 1년 이상은 15일 기준... | 인사규정_휴가.pdf |
| VPN 신청은 어디서 하나요? | IT 포털의 보안 신청 메뉴에서 신청... | IT가이드_VPN.md |

---

## 12. Metadata 활용

메타데이터를 잘 설계하면 검색 품질과 권한 관리가 좋아집니다.

### 주요 메타데이터
- 문서 제목
- 작성일 / 수정일
- 문서 유형
- 부서
- 제품명
- 버전
- 언어
- 권한 등급
- 유효 여부
- 원본 URL

### 활용 예
- 최신 문서 우선 검색
- 특정 부서 문서만 검색
- 사용자가 접근 가능한 문서만 retrieval
- 제품 버전별 필터링

---

## 13. 권한 및 보안

RAG에서는 검색 단계에서 권한 처리가 매우 중요합니다.

### 검토 사항
- 사용자가 접근 권한 없는 문서를 검색하지 않는가?
- 검색 결과에 민감정보가 포함되지 않는가?
- 로그에 개인정보가 저장되지 않는가?
- 문서별 ACL이 Vector DB에도 반영되는가?

### 개선 방향
- Retrieval 단계에서 권한 필터링
- 민감정보 마스킹
- 감사 로그 관리
- 사용자별 문서 접근 범위 적용

---

## 14. Vector DB 설정

Vector DB의 설정도 검색 품질과 속도에 영향을 줍니다.

### 확인할 사항
- index 방식이 적절한가?
- cosine, dot product, L2 중 적합한 거리 척도를 사용하는가?
- top-k 값이 적절한가?
- approximate search 설정으로 인해 recall이 낮아지지 않는가?
- 필터 검색 성능은 충분한가?

### 개선 방향
- HNSW, IVF 등 index 파라미터 튜닝
- top-k 실험
- hybrid search 지원 여부 확인
- metadata filtering 성능 검증

---

## 15. 응답 속도와 비용

성능이 좋아도 느리거나 비용이 높으면 운영이 어렵습니다.

### 병목 구간
- Embedding 생성
- Vector 검색
- Reranking
- LLM 응답 생성
- 긴 context 처리

### 개선 방향
- query/result caching
- embedding cache
- reranker 적용 범위 제한
- top-k 조정
- 작은 모델과 큰 모델의 라우팅
- 스트리밍 응답 적용

---

## 16. Hallucination 방지

RAG의 중요한 목적 중 하나는 hallucination 감소입니다.

### 개선 방향
- 근거 없는 답변 금지 prompt
- citation 강제
- context relevance 검증
- 답변 후 self-check
- 문서에 없는 질문은 답변 거절
- 낮은 confidence일 경우 추가 질문 유도

### 예시 답변 정책
```text
제공된 문서에서 확인 가능한 내용은 다음과 같습니다...
다만, 요청하신 XXX에 대한 정보는 제공된 문서에서 확인할 수 없습니다.
```

---

## 17. 질의 유형별 전략 분리

모든 질문을 동일한 방식으로 처리하면 성능 한계가 있습니다.

### 예시 유형
| 질문 유형 | 전략 |
|---|---|
| 단순 FAQ | 빠른 keyword/vector 검색 |
| 정책 질의 | 최신 문서 + 권한 필터링 |
| 비교 질의 | 여러 문서 검색 후 종합 |
| 수치/날짜 질의 | 정확한 근거 문장 인용 |
| 절차 질의 | 단계별 답변 |
| 요약 요청 | 긴 문서 summarization |
| 코드 질의 | 코드 단위 chunk 검색 |

---

## 18. 운영 모니터링

배포 후에도 지속적으로 성능을 추적해야 합니다.

### 모니터링 항목
- 검색 실패 질문
- 답변 불만족 사례
- hallucination 사례
- 자주 묻는 질문
- 문서 부재로 인한 실패
- 응답 지연 구간
- 비용 증가 원인

### 개선 루프
1. 사용자 로그 수집
2. 실패 질문 분류
3. 문서 보강 또는 chunk 개선
4. 검색 전략 수정
5. 평가셋 재실행
6. 재배포

---

# 핵심 체크리스트

| 영역 | 주요 검토 사항 |
|---|---|
| 데이터 | 최신성, 중복, 파싱 품질 |
| Chunking | 크기, overlap, 구조 보존 |
| Embedding | 한국어/도메인 적합성 |
| 검색 | Hybrid search, metadata filtering |
| Reranking | 관련도 재정렬 |
| Query | query rewrite, expansion |
| Prompt | 근거 기반 답변, 모르면 모른다고 답변 |
| Evaluation | Recall@K, Faithfulness, 사용자 만족도 |
| 보안 | 권한 필터링, 민감정보 보호 |
| 운영 | 속도, 비용, 로그 기반 개선 |

---

## 우선 적용 추천 순서

1. **평가셋 구축**
2. **문서 품질 및 chunking 점검**
3. **Embedding 모델 비교**
4. **Hybrid Search 적용**
5. **Reranker 적용**
6. **Prompt 및 citation 개선**
7. **운영 로그 기반 반복 개선**

RAG 성능 개선은 단일 모델 교체보다 **데이터 정비 → 검색 품질 개선 → 답변 제어 → 평가 자동화**의 순서로 접근하는 것이 효과적입니다.

### Memory

In [ ]:
from langchain.chat_models import init_chat_model

# 모델 객체 생성
model = init_chat_model("gpt-5.4-mini")

In [ ]:
response = model.invoke("내 이름은 홍길동이야")

In [ ]:
response.content

'반가워요, 홍길동님! 무엇을 도와드릴까요?'

In [ ]:
response2 = model.invoke("내 이름이 뭐라고?")

In [ ]:
response2.content

'지금 대화만으로는 당신의 이름을 알 수 없어요.  \n원하시면 이름을 알려주시면 그 이름으로 불러드릴게요.'

#### 과거 대화 맥락 전달 1

In [ ]:
from langchain.messages import HumanMessage, AIMessage, SystemMessage

sys_msg = SystemMessage("당신은 유치원 교사입니다. 아이들에게 친절히 답변하세요.")
human_msg = HumanMessage("안녕! 난 홍길동이야!")
human_msg2 = HumanMessage("내 이름이 뭐라고?")

In [ ]:
messages = [sys_msg, human_msg, human_msg2]

In [ ]:
response = model.invoke(messages)

In [ ]:
response.content

'안녕, 홍길동! 반가워 😊  \n네 이름은 **홍길동**이야!'

#### 과거 대화 맥락 전달 2

In [ ]:
messages = [
    {"role": "system", "content": "당신은 유능한 로켓 전문가입니다."},
    {"role": "human", "content": "안녕하세요. 궁금한 게 있어요!"},
    {"role": "ai", "content": "로켓 관련 무엇이든 물어보세요."},
    {"role": "human", "content": "추진 방식 차이를 설명해 주세요"},
]

In [ ]:
response = model.invoke(messages)

In [ ]:
response.content

'물론입니다. 로켓의 **추진 방식**은 “무엇을 어떻게 밀어내서 앞으로 나아가느냐”의 차이입니다. 대표적으로 아래처럼 구분할 수 있어요.\n\n## 1) 화학 로켓\n연료와 산화제를 태워서 뜨거운 고온·고압의 가스를 만들고, 그 가스를 노즐로 뒤로 뿜어 추진합니다.\n\n- **장점**: 추력이 매우 큼, 구조가 비교적 단순, 현재 가장 널리 사용\n- **단점**: 효율에는 한계가 있음, 연료 소모가 큼\n- **예**: 발사체, 우주선 이륙용 엔진\n\n### 세부 종류\n- **고체 로켓**\n  - 연료와 산화제가 고체에 섞여 있음\n  - 장점: 단순, 보관 쉬움, 즉시 점화 가능\n  - 단점: 한 번 점화하면 끄거나 조절하기 어려움\n- **액체 로켓**\n  - 연료와 산화제를 액체로 분리 저장\n  - 장점: 추력 조절 가능, 재점화 가능, 성능 우수\n  - 단점: 구조 복잡, 냉각·펌프 시스템 필요\n- **하이브리드 로켓**\n  - 한쪽은 고체, 다른 쪽은 액체 또는 기체\n  - 장점: 고체보다 제어가 쉽고 액체보다 단순\n  - 단점: 성능과 기술 완성도가 아직 제한적\n\n---\n\n## 2) 전기추진\n전기를 이용해 추진제를 매우 빠른 속도로 분사합니다. 보통 **아주 작은 추력**을 오랫동안 내는 방식입니다.\n\n- **장점**: 연료 효율이 매우 좋음, 장시간 운용에 적합\n- **단점**: 추력이 작아 지구 이륙에는 부적합\n- **예**: 위성 궤도 유지, 심우주 탐사선\n\n### 대표 방식\n- **이온 엔진**: 이온을 전기장으로 가속\n- **홀 효과 추진기**: 전기장과 자기장을 이용해 가스 이온을 가속\n\n---\n\n## 3) 핵추진\n핵반응에서 나오는 에너지를 이용해 추진제를 가열하거나, 직접 추진에 활용합니다.\n\n- **장점**: 화학 로켓보다 더 높은 효율 가능\n- **단점**: 방사선, 안전성, 정치적·기술적 제약이 큼\n- **예**: 핵열로켓, 핵전기추진 개념\n\n---\n\n## 4) 이론적/미래형 추진\n아직 실용화되지 않았거나 연구 단계인 방식입니다.\n\n- **태양돛**: 태양빛의 압력을 이용\n- **레이저 추진**: 외부에서 쏘는 레이저로 가속\n- **반물질 추진**: 에너지 밀도는 크지만 현실적 구현 어려움\n\n---\n\n## 핵심 차이 한눈에 보기\n\n| 방식 | 추력 | 효율 | 복잡도 | 주 용도 |\n|---|---:|---:|---:|---|\n| 고체 로켓 | 큼 | 보통 | 낮음 | 발사 보조, 군용 |\n| 액체 로켓 | 큼 | 높음 | 높음 | 발사체, 우주선 |\n| 하이브리드 | 중간 | 중간 | 중간 | 연구, 일부 시험용 |\n| 전기추진 | 작음 | 매우 높음 | 중간~높음 | 위성, 심우주 |\n| 핵추진 | 매우 큼/고효율 가능 | 매우 높음 | 매우 높음 | 미래 탐사 개념 |\n\n원하시면 다음 중 하나로 더 자세히 설명해 드릴게요:\n1. **고체 vs 액체 로켓 차이**\n2. **전기추진이 왜 효율적인지**\n3. **로켓의 추력과 비추력(특성속도) 차이**'

### 구조화된 답변

#### Pydantic

In [ ]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.15.0
access                                1.1.10.post3
affine                                3.0.1
aiofiles                              25.1.0
aiohappyeyeballs                      2.7.1
aiohttp                               3.14.3
aiosignal                             1.4.0
aiosqlite                             0.22.1
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.12.1
altair                                5.5.0
annotated-doc                         0.0.5
annotated-types                       0.8.0
antlr4-python3-runtime                4.9.3
anyio                                 4.15.1
anywidget                             0.9.21
apsw                                  3.53.4.0
argon2-cffi                           25.1.0
argon2-cffi-bindings                  26.1.0
array_record                          0.8.3
arrow                                 1.4.0
arviz                                 0.22.0
astropy                               7.2.2
astropy-iers-data                     0.2026.9.28.0.59.37
astunparse                            1.6.3
atpublic                              5.1
attrs                                 26.1.0
audioop-lts                           0.2.2
audioread                             3.1.0
Authlib                               1.8.0
autograd                              1.9.1
babel                                 2.18.0
backcall                              0.2.0
beartype                              0.22.9
beautifulsoup4                        4.13.5
betterproto                           2.0.0b7
bigframes                             2.49.0
bigquery-magics                       0.14.0
bleach                                6.4.0
blinker                               1.9.0
blis                                  1.3.3
blobfile                              3.3.0
blosc2                                4.14.1
bokeh                                 3.8.2
Bottleneck                            1.4.2
bqplot                                0.12.47
branca                                0.8.2
brotli                                1.2.0
CacheControl                          0.14.4
cachetools                            6.2.6
catalogue                             2.0.10
certifi                               2026.7.22
cffi                                  2.1.1
chardet                               5.2.0
charset-normalizer                    3.4.9
clarabel                              0.11.1
click                                 8.5.0
cligj                                 0.7.2
cloudpathlib                          0.25.0
cloudpickle                           3.1.2
cmake                                 3.31.10
cmdstanpy                             1.3.0
colorcet                              3.2.1
colorlover                            0.3.0
community                             1.0.0b1
confection                            1.3.3
cons                                  0.4.7
contourpy                             1.4.0
cpsat-logutils                        1.0.0
cramjam                               2.13.0
cryptography                          50.0.2
cufflinks                             0.17.3
curl_cffi                             0.16.3
cvxopt                                1.3.2
cvxpy                                 1.6.7
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.13
Cython                                3.0.12
dask                                  2026.8.0
dataproc-spark-connect                1.1.0
datasets                              4.8.5
db-dtypes                             1.7.1
dbus-python                           1.3.2
debugpy                               1.8.15
decorator                             4.4.2
defusedxml                            0.7.1
deprecation                           2.1.0
diffusers                             0.40.0
dill                                  0.4.1
distributed                           2026.8.0
distro                                1.9.0
dlib                                  20.0.1
dm-tree                               0.1.10
docstring_parser                      0.18.0
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.3.2
earthengine-api                       1.7.39
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.3
einops                                0.8.2
en_core_web_sm                        3.8.0
entrypoints                           0.4
esda                                  2.9.0
et_xmlfile                            2.0.0
etils                                 1.14.0
etuples                               0.3.10
Farama-Notifications                  0.0.6
fastai                                2.8.12
fastapi                               0.141.1
fastcore                              2.2.32
fastdownload                          0.0.8
fastjsonschema                        2.22.2
fastprogress                          1.1.6
fasttransform                         0.0.5
filelock                              4.0.7
firebase-admin                        6.9.0
Flask                                 3.1.3
flatbuffers                           25.12.19
flax                                  0.11.2
folium                                0.20.0
fonttools                             4.66.1
formulaic                             1.2.2
fqdn                                  1.6.0
frozendict                            2.4.7
frozenlist                            1.8.0
fsspec                                2025.12.0
future                                1.0.0
gast                                  0.7.0
gcsfs                                 2025.12.0
GDAL                                  3.8.4
gdown                                 5.2.2
geemap                                0.38.8
geocoder                              1.38.1
geographiclib                         2.1
geopandas                             1.2.0
geopy                                 2.4.1
giddy                                 2.3.9
gin-config                            0.5.0
glob2                                 0.7
google                                3.0.0
google-adk                            2.7.1
google-api-core                       2.30.3
google-api-python-client              2.201.0
google-auth                           2.49.0
google-auth-httplib2                  0.4.3
google-auth-oauthlib                  1.5.0
google-cloud-bigquery                 3.45.2
google-cloud-bigquery-connection      1.22.0
google-cloud-bigquery-storage         2.41.0
google-cloud-core                     2.8.0
google-cloud-dataproc                 5.30.0
google-cloud-datastore                2.26.1
google-cloud-firestore                2.33.0
google-cloud-functions                1.24.0
google-cloud-language                 2.21.0
google-cloud-monitoring               2.31.0
google-cloud-resource-manager         1.18.0
google-cloud-spanner                  3.71.0
google-cloud-storage                  3.15.1
google-cloud-storage-control          1.15.0
google-cloud-translate                3.27.0
google-colab                          1.0.0
google-crc32c                         1.9.0
google-genai                          2.12.1
google-pasta                          0.2.0
google-resumable-media                2.11.0
googleapis-common-protos              1.75.5
googledrivedownloader                 1.1.0
gradio                                6.29.0
gradio_client                         2.7.1
grain                                 0.2.18
graphviz                              0.21
groovy                                0.1.2
grpc-google-iam-v1                    0.14.5
grpc-interceptor                      0.15.4
grpcio                                1.84.0
grpcio-status                         1.84.0
grpclib                               0.4.9
gspread                               6.2.1
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.1.0
gymnasium                             1.3.0
h11                                   0.16.0
h2                                    4.4.1
h5netcdf                              1.8.1
h5py                                  3.14.0
hdbscan                               0.8.44
hf-gradio                             0.4.1
hf-xet                                1.6.0
highspy                               1.15.1
holidays                              0.105
holoviews                             1.23.2
hpack                                 4.2.0
html5lib                              1.1
httpcore                              1.0.9
httpcore2                             2.13.1
httpimport                            1.4.1
httplib2                              0.32.0
httptools                             0.8.0
httpx                                 0.28.1
httpx2                                2.13.1
huggingface_hub                       1.33.0
humanize                              4.16.0
hyperframe                            6.1.0
hyperopt                              0.3.0
ibis-framework                        9.5.0
idna                                  3.20
ImageIO                               2.38.0
imageio-ffmpeg                        0.6.0
imagesize                             2.0.1
imbalanced-learn                      0.14.2
immutabledict                         4.3.1
importlib_metadata                    9.0.1
imutils                               0.5.4
inequality                            1.1.2
inflect                               7.5.0
iniconfig                             2.3.0
intel-cmplr-lib-ur                    2025.3.3
intel-openmp                          2025.3.3
interface_meta                        2.0.1
ipyevents                             2.0.4
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.20.0
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipywidgets                            7.7.1
isoduration                           20.11.0
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.1.2
jaraco.functools                      4.6.0
jax                                   0.11.1
jaxlib                                0.11.1
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.17.0
joblib                                1.6.0
joserfc                               1.7.5
jsonpatch                             1.33
jsonpickle                            4.1.2
jsonpointer                           3.1.1
jsonschema                            4.26.0
jsonschema-specifications             2025.9.1
jupyter_client                        7.4.9
jupyter-console                       6.6.3
jupyter_core                          5.9.1
jupyter-events                        0.12.1
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.20.0
jupyter_server                        2.20.0
jupyter_server_terminals              0.5.4
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.17
jupytext                              1.19.5
kaggle                                2.0.2
kagglehub                             1.0.2
kagglesdk                             0.1.37
keras                                 3.13.2
keras-hub                             0.26.0
keras-nlp                             0.26.0
keyring                               25.7.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.5.1
langchain                             1.4.3
langchain-core                        1.6.9
langchain-openai                      1.7.0
langchain-protocol                    0.0.19
langgraph                             1.2.12
langgraph-checkpoint                  4.2.0
langgraph-prebuilt                    1.1.0
langgraph-sdk                         0.4.5
langsmith                             0.14.2
lark                                  1.3.1
launchpadlib                          1.11.0
lazr.restfulclient                    0.14.6
lazr.uri                              1.0.6
lazy-loader                           0.6
libclang                              18.1.1
libpysal                              4.14.1
librosa                               0.11.0
lightgbm                              4.6.0
linkify-it-py                         2.2.0
llvmlite                              0.44.0
locket                                1.0.0
logical-unification                   0.4.7
lxml                                  6.1.3
lz4                                   4.4.5
Mako                                  1.3.2.dev0
mapclassify                           2.10.0
Markdown                              3.11
markdown-it-py                        4.2.0
MarkupSafe                            3.0.3
matplotlib                            3.10.0
matplotlib-inline                     0.2.2
matplotlib-venn                       1.1.2
mdit-py-plugins                       0.6.1
mdurl                                 0.1.2
mgwr                                  2.2.1
miniKanren                            1.0.5
missingno                             0.5.2
mistune                               3.3.4
mizani                                0.13.5
mkl                                   2025.3.1
ml_dtypes                             0.6.0
mlxtend                               0.23.4
mmh3                                  5.3.1
momepy                                0.11.0
more-itertools                        10.8.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.2.3
multidict                             6.9.1
multipledispatch                      1.0.0
multiprocess                          0.70.19
multitasking                          0.0.13
murmurhash                            1.0.15
music21                               9.9.2
namex                                 0.1.0
narwhals                              2.26.0
natsort                               8.4.0
nbclassic                             1.3.3
nbclient                              0.10.4
nbconvert                             7.17.1
nbformat                              5.11.1
ndindex                               1.10.1
nest-asyncio                          1.6.0
networkx                              3.7
nh3                                   0.3.7
nibabel                               5.4.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.61.2
numexpr                               2.14.2
numpy                                 2.1.3
nvidia-nccl-cu13                      2.32.3
oauth2client                          4.1.3
oauthlib                              3.3.1
omegaconf                             2.3.1
onemkl-license                        2025.3.1
openai                                2.54.0
opencv-contrib-python                 4.14.0.94
opencv-python                         5.0.0.93
opencv-python-headless                5.0.0.93
openpyxl                              3.1.5
opentelemetry-api                     1.42.1
opentelemetry-resourcedetector-gcp    1.14.0
opentelemetry-sdk                     1.42.1
opentelemetry-semantic-conventions    0.63b1
opt_einsum                            3.4.0
optax                                 0.2.8
optree                                0.20.0
orbax-checkpoint                      0.12.6
orjson                                3.12.0
orloge                                1.0.0
ormsgpack                             1.12.2
osqp                                  1.1.3
packaging                             26.3
pandas                                2.2.3
pandas-datareader                     0.11.1
pandas-gbq                            0.30.0
pandas-stubs                          2.2.3.250527
pandocfilters                         1.5.1
panel                                 1.9.4
panel-material-ui                     0.16.0
param                                 2.4.2
parso                                 0.8.7
parsy                                 2.2
partd                                 1.4.2
patsy                                 1.0.3
peewee                                4.5.2
peft                                  0.21.1
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.3.0
pip                                   24.1.2
platformdirs                          4.12.2
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.6.0
plum-dispatch                         2.9.0
pointpats                             2.5.5
polars                                1.35.2
polars-runtime-32                     1.35.2
pooch                                 1.9.0
portpicker                            1.5.2
preshed                               3.0.13
prettytable                           3.18.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.26.0
promise                               2.3
prompt_toolkit                        3.0.53
propcache                             0.5.4
prophet                               1.4.0
proto-plus                            1.29.0
protobuf                              6.33.6
psutil                                5.9.5
psycopg2                              2.9.13
psygnal                               0.16.1
ptyprocess                            0.7.0
PuLP                                  4.0.0
py-cpuinfo                            9.0.0
py4j                                  0.10.9.9
pyarrow                               23.0.1
pyasn1                                0.6.4
pyasn1_modules                        0.4.2
pycairo                               1.29.1
pycocotools                           2.0.11
pycparser                             3.0
pycryptodomex                         3.23.0
pydantic                              2.13.5
pydantic_core                         2.46.5
pydata-google-auth                    1.9.1
pydot                                 4.0.1
pydotplus                             2.0.2
PyDrive2                              1.21.1
pydub                                 0.25.1
pyerfa                                2.0.1.5
pygame                                2.6.1
pygit2                                1.20.1
Pygments                              2.21.0
PyGObject                             3.48.2
pyiceberg                             0.12.0
PyJWT                                 2.15.1
pymc                                  5.28.5
pynndescent                           0.6.0
pyogrio                               0.13.0
pyomo                                 6.10.1
PyOpenGL                              3.1.10
pyOpenSSL                             26.4.0
pyparsing                             3.3.3
pyperclip                             1.11.0
pyproj                                3.8.0
pyroaring                             1.1.0

In [ ]:
# pydantic
from pydantic import BaseModel, Field

class Movie(BaseModel):
    "영화에 대한 상세한 정보"
    title : str = Field(description="이 영화의 제목")
    year : int = Field(description="이 영화의 개봉 연도")
    rating : float = Field(description="이 영화에 대한 평점")

In [ ]:
model = init_chat_model("gpt-5.5")

In [ ]:
# with_structured_output
model_with_structure = model.with_structured_output(Movie)

In [ ]:
model_with_structure

_ChatModelBinding(bound=ChatOpenAI(metadata={'lc_versions': {'langchain-core': '1.6.9', 'langchain': '1.4.3', 'langchain-openai': '1.7.0'}}, profile={'name': 'GPT-5.5', 'release_date': '2026-04-23', 'last_updated': '2026-04-23', 'open_weights': False, 'max_input_tokens': 1050000, 'max_output_tokens': 128000, 'text_inputs': True, 'image_inputs': True, 'audio_inputs': False, 'pdf_inputs': True, 'video_inputs': False, 'text_outputs': True, 'image_outputs': False, 'audio_outputs': False, 'video_outputs': False, 'reasoning_output': True, 'tool_calling': True, 'structured_output': True, 'attachment': True, 'temperature': False, 'image_url_inputs': True, 'pdf_tool_message': True, 'image_tool_message': True, 'tool_choice': True, 'tool_call_streaming': True, 'reasoning_effort_levels': ['none', 'low', 'medium', 'high', 'xhigh'], 'reasoning_effort_default': 'medium'}, client=<openai.resources.chat.completions.completions.Completions object at 0x7dcf4ebdf890>, async_client=<openai.resources.chat.completions.completions.AsyncCompletions object at 0x7dcf4ebdfc50>, root_client=<openai.OpenAI object at 0x7dcf4ebded50>, root_async_client=<openai.AsyncOpenAI object at 0x7dcf4ebdf9d0>, model_name='gpt-5.5', model_kwargs={}, openai_api_key=SecretStr('**********'), stream_usage=True, stream_chunk_timeout=120.0), kwargs={'response_format': <class '__main__.Movie'>, 'ls_structured_output_format': {'kwargs': {'method': 'json_schema', 'strict': None}, 'schema': {'type': 'function', 'function': {'name': 'Movie', 'description': '영화에 대한 상세한 정보', 'parameters': {'properties': {'title': {'description': '이 영화의 제목', 'type': 'string'}, 'year': {'description': '이 영화의 개봉 연도', 'type': 'integer'}, 'rating': {'description': '이 영화에 대한 평점', 'type': 'number'}}, 'required': ['title', 'year', 'rating'], 'type': 'object'}}}}}, config={}, config_factories=[])
| RunnableBinding(bound=RunnableLambda(...), kwargs={}, config={}, config_factories=[], custom_output_type=<class '__main__.Movie'>)

In [ ]:
response = model_with_structure.invoke("영화 인셉션에 대해 설명해 주세요")

In [ ]:
model.invoke("영화 인셉션에 대해 설명해 주세요")

AIMessage(content='《인셉션》(Inception, 2010)은 크리스토퍼 놀란 감독의 SF 스릴러 영화로, “꿈속에 들어가 생각을 훔치거나 심을 수 있다”는 설정을 바탕으로 한 작품입니다.\n\n주인공 돔 코브는 사람의 꿈에 침투해 무의식 속 정보를 훔치는 전문가입니다. 그는 과거의 사건 때문에 가족에게 돌아가지 못하는 처지에 놓여 있고, 어느 날 거대 기업가 사이토로부터 특별한 제안을 받습니다. 그것은 정보를 훔치는 것이 아니라, 한 사람의 마음속에 특정한 생각을 심는 일, 즉 ‘인셉션’을 수행하는 것입니다.\n\n영화의 핵심은 여러 겹으로 이루어진 꿈의 구조입니다. 꿈속에서 또 다른 꿈으로 들어갈수록 시간은 더 느리게 흐르고, 현실과 꿈의 경계는 점점 모호해집니다. 코브와 팀원들은 목표 인물인 피셔의 무의식 깊숙이 들어가 그의 생각을 바꾸려 하지만, 코브 자신의 죄책감과 기억이 임무를 방해합니다.\n\n이 영화는 단순한 액션 영화라기보다 다음과 같은 주제를 다룹니다.\n\n- 현실과 꿈의 경계  \n- 기억과 죄책감  \n- 무의식의 힘  \n- 사랑과 집착  \n- 인간이 믿고 싶은 현실  \n\n특히 마지막 장면의 팽이 장면은 유명합니다. 팽이가 계속 도는지, 멈추는지 확실히 보여주지 않으면서 관객에게 “이것이 현실인가, 꿈인가?”라는 질문을 남깁니다. 그래서 《인셉션》은 결말 해석에 대해 지금까지도 많은 논쟁이 있는 영화입니다.\n\n정리하면, 《인셉션》은 복잡한 꿈의 세계를 배경으로 한 범죄 작전 영화이면서, 동시에 인간의 기억과 현실 인식에 대해 질문을 던지는 작품입니다.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 484, 'prompt_tokens': 17, 'total_tokens': 501, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 37, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.5-2026-04-23', 'system_fingerprint': None, 'id': 'chatcmpl-EXfRbK7frOZhw9U1te95LLTQqPg2C', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a12937-250c-7f53-9666-4aa1427afc41-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 17, 'output_tokens': 484, 'total_tokens': 501, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 37}})

In [ ]:
response

Movie(title='인셉션', year=2010, rating=8.8)

In [ ]:
type(response)

__main__.Movie

In [ ]:
result = response.model_dump()

In [ ]:
result

{'title': '인셉션', 'year': 2010, 'rating': 8.8}

In [ ]:
type(result)

dict

In [ ]:
result['title']

'인셉션'

#### JSON output parser

In [ ]:
import json

json_schema = {
    "title": "Movie",
    "description": "A movie with details",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "The title of the movie"
        },
        "year": {
            "type": "integer",
            "description": "The year the movie was released"
        },
        "director": {
            "type": "string",
            "description": "The director of the movie"
        },
        "rating": {
            "type": "number",
            "description": "The movie's rating out of 10"
        }
    },
    "required": ["title", "year", "director", "rating"]
}

In [ ]:
model_with_structure = model.with_structured_output(json_schema)

In [ ]:
model_with_structure

_ChatModelBinding(bound=ChatOpenAI(metadata={'lc_versions': {'langchain-core': '1.6.9', 'langchain': '1.4.3', 'langchain-openai': '1.7.0'}}, profile={'name': 'GPT-5.5', 'release_date': '2026-04-23', 'last_updated': '2026-04-23', 'open_weights': False, 'max_input_tokens': 1050000, 'max_output_tokens': 128000, 'text_inputs': True, 'image_inputs': True, 'audio_inputs': False, 'pdf_inputs': True, 'video_inputs': False, 'text_outputs': True, 'image_outputs': False, 'audio_outputs': False, 'video_outputs': False, 'reasoning_output': True, 'tool_calling': True, 'structured_output': True, 'attachment': True, 'temperature': False, 'image_url_inputs': True, 'pdf_tool_message': True, 'image_tool_message': True, 'tool_choice': True, 'tool_call_streaming': True, 'reasoning_effort_levels': ['none', 'low', 'medium', 'high', 'xhigh'], 'reasoning_effort_default': 'medium'}, client=<openai.resources.chat.completions.completions.Completions object at 0x7dcf4ebdf890>, async_client=<openai.resources.chat.completions.completions.AsyncCompletions object at 0x7dcf4ebdfc50>, root_client=<openai.OpenAI object at 0x7dcf4ebded50>, root_async_client=<openai.AsyncOpenAI object at 0x7dcf4ebdf9d0>, model_name='gpt-5.5', model_kwargs={}, openai_api_key=SecretStr('**********'), stream_usage=True, stream_chunk_timeout=120.0), kwargs={'response_format': {'type': 'json_schema', 'json_schema': {'name': 'Movie', 'description': 'A movie with details', 'strict': False, 'schema': {'type': 'object', 'properties': {'title': {'type': 'string', 'description': 'The title of the movie'}, 'year': {'type': 'integer', 'description': 'The year the movie was released'}, 'director': {'type': 'string', 'description': 'The director of the movie'}, 'rating': {'type': 'number', 'description': "The movie's rating out of 10"}}, 'required': ['title', 'year', 'director', 'rating']}}}, 'ls_structured_output_format': {'kwargs': {'method': 'json_schema', 'strict': None}, 'schema': {'type': 'function', 'function': {'name': 'Movie', 'description': 'A movie with details', 'parameters': {'type': 'object', 'properties': {'title': {'type': 'string', 'description': 'The title of the movie'}, 'year': {'type': 'integer', 'description': 'The year the movie was released'}, 'director': {'type': 'string', 'description': 'The director of the movie'}, 'rating': {'type': 'number', 'description': "The movie's rating out of 10"}}, 'required': ['title', 'year', 'director', 'rating']}}}}}, config={}, config_factories=[])
| JsonOutputParser()

In [ ]:
response = model_with_structure.invoke("영화 인셉션에 대해서 소개해 주세요")

In [ ]:
response

{'title': '인셉션 (Inception)',
 'year': 2010,
 'director': '크리스토퍼 놀란',
 'rating': 8.8}

## Agents

### Tool 기초

In [ ]:
model = init_chat_model("gpt-5.4-mini")

In [ ]:
response = model.invoke("현재 서울 날씨 어때?")

In [ ]:
response.content

'죄송하지만 저는 **실시간 날씨 데이터에 직접 접속할 수는 없어서** 지금 서울의 현재 날씨를 바로 확인해드리진 못해요.\n\n대신 빠르게 확인하는 방법은:\n- **네이버 날씨**: “서울 날씨” 검색\n- **기상청 날씨누리**\n- **구글에** “서울 현재 날씨” 검색\n\n원하시면 제가 대신  \n- **오늘 서울 날씨 확인하는 가장 빠른 방법**  \n- **외출용 옷차림 추천**  \n- **비/미세먼지 여부를 확인하는 법**  \n까지 바로 정리해드릴게요.'

In [ ]:
# 도구 생성
from langchain.tools import tool

@tool
def get_weather(location : str) -> str:
    "특정 지역의 날씨 정보를 제공"
    return f"{location}의 날씨는 현재 -2도에 미세먼지는 매우 나쁨입니다."

In [ ]:
# 에이전트 생성
from langchain.agents import create_agent

agent = create_agent(model, tools=[get_weather])

In [ ]:
# 에이전트 실행
result = agent.invoke(
    {"messages" : [{"role" : "user", "content" : "오늘 제주도 날씨 어때요?"}]}
)

In [ ]:
# 응답 출력 1
result['messages'][-1].content

'제주도 날씨는 현재 **-2도**이고, **미세먼지는 매우 나쁨**입니다.  \n외출하신다면 **따뜻하게 입고**, 가능하면 **마스크 착용**을 추천드려요.'

In [ ]:
# 응답 출력 2
result

{'messages': [HumanMessage(content='오늘 제주도 날씨 어때요?', additional_kwargs={}, response_metadata={}, id='d56d45e3-0b09-4013-a6e8-6f5ebfd368c0'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 19, 'prompt_tokens': 135, 'total_tokens': 154, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXg1e3suyFlvvpRvQjDapOtUpt9Dl', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a12959-408e-78c2-aa60-7689fae8e6ec-0', tool_calls=[{'name': 'get_weather', 'args': {'location': '제주도'}, 'id': 'call_XmGkOA8QqJskMh9XolgGrnRl', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 135, 'output_tokens': 19, 'total_tokens': 154, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='제주도의 날씨는 현재 -2도에 미세먼지는 매우 나쁨입니다.', name='get_weather', id='484db274-296d-4859-a3f3-b160415042f4', tool_call_id='call_XmGkOA8QqJskMh9XolgGrnRl'),
  AIMessage(content='제주도 날씨는 현재 **-2도**이고, **미세먼지는 매우 나쁨**입니다.  \n외출하신다면 **따뜻하게 입고**, 가능하면 **마스크 착용**을 추천드려요.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 56, 'prompt_tokens': 186, 'total_tokens': 242, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXg1e8U95ZIOpM5aXe0IRLEHDfrRq', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a12959-44a8-7792-801a-3dc6804e71aa-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 186, 'output_tokens': 56, 'total_tokens': 242, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}

In [ ]:
# 1. 모델 생성
model = init_chat_model("gpt-5.4-mini")

# 2. 도구 생성
@tool
def add(a: float, b: float) -> float:
    """두 숫자를 더합니다."""
    return a + b

@tool
def subtract(a: float, b: float) -> float:
    """첫 번째 숫자에서 두 번째 숫자를 뺍니다."""
    return a - b

# 3. 에이전트 생성
agent = create_agent(
    model,
    tools=[add, subtract]
)

# 4. 에이전트 실행
result = agent.invoke(
    {"messages": [
        {"role": "user", "content": "274에 356을 더하고 187을 빼면 뭐야?"}
    ]}
)

# 5. 최종 응답
result["messages"][-1].content

'274에 356을 더하면 630이고, 거기서 187을 빼면 **443**입니다.'

In [ ]:
result

{'messages': [HumanMessage(content='274에 356을 더하고 187을 빼면 뭐야?', additional_kwargs={}, response_metadata={}, id='5d58ca46-e51b-4664-8927-00b5bd9bb78c'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 53, 'prompt_tokens': 174, 'total_tokens': 227, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXg9pj94IoPrSNNqA5Z6fP0menYpk', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a12960-fcbe-7201-a82c-0cf599b00550-0', tool_calls=[{'name': 'add', 'args': {'a': 274, 'b': 356}, 'id': 'call_awADRxqDzoAMLOgJnalZjFQi', 'type': 'tool_call'}, {'name': 'subtract', 'args': {'a': 630, 'b': 187}, 'id': 'call_vEFFJrKiCA374k4S41NzhYq3', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 174, 'output_tokens': 53, 'total_tokens': 227, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='630.0', name='add', id='cb77c1b8-6c56-4742-a63b-5a7275ef0a54', tool_call_id='call_awADRxqDzoAMLOgJnalZjFQi'),
  ToolMessage(content='443.0', name='subtract', id='cd3484be-8678-46be-9d1d-b8c187c2837a', tool_call_id='call_vEFFJrKiCA374k4S41NzhYq3'),
  AIMessage(content='274에 356을 더하면 630이고, 거기서 187을 빼면 **443**입니다.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 28, 'prompt_tokens': 250, 'total_tokens': 278, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXg9qb23gzHhGhBHpEymlMtpP7ZYn', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a12961-0221-71e3-9be7-39f11406203f-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 250, 'output_tokens': 28, 'total_tokens': 278, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}

#### 에이전트 구축 실습 1

datetime 라이브러리 [참고 링크](https://wikidocs.net/227592)

In [ ]:
import datetime

# UTC 기준 시간
utc_now = datetime.datetime.now(datetime.timezone.utc)

# 한국 시간으로 변환 (UTC + 9시간)
kst_timezone = datetime.timezone(datetime.timedelta(hours=9))
kst_now = utc_now.astimezone(kst_timezone)

print(f"현재 한국 시간: {kst_now.strftime('%Y-%m-%d %H:%M')}")

현재 한국 시간: 2026-10-11 15:11

In [ ]:
@tool
def get_current_korea_time() -> str :
  "한국의 현재 날짜와 시간을 반환합니다."
  # UTC 기준 시간
  utc_now = datetime.datetime.now(datetime.timezone.utc)

  # 한국 시간으로 변환 (UTC + 9시간)
  kst_timezone = datetime.timezone(datetime.timedelta(hours=9))
  kst_now = utc_now.astimezone(kst_timezone)

  return f"현재 한국 시간: {kst_now.strftime('%Y-%m-%d %H:%M')}"

In [ ]:
agent = create_agent(model, tools=[get_current_korea_time])

In [ ]:
result = agent.invoke(
    {"messages" : [{"role" : "user", "content" : "현재 한국은 몇월 며칠 몇 시 몇분이야?"}]}
)

In [ ]:
result['messages'][-1].content

'현재 한국 시간은 **2026년 10월 11일 15시 13분**입니다.'

### 에이전트 구축 2

In [ ]:
from langchain.tools import tool

@tool
def add(a: int, b: int) -> int:
    """`a`와 `b` 덧셈.

    Args:
        a: First int
        b: Second int
    """
    return a + b

@tool
def multiply(a: int, b: int) -> int:
    """`a`와 `b` 곱셈.

    Args:
        a: First int
        b: Second int
    """
    return a * b

@tool
def divide(a: int, b: int) -> float:
    """`a`와 `b` 나눗셈.

    Args:
        a: First int
        b: Second int
    """
    return a / b

In [ ]:
tools = [add, multiply, divide]

In [ ]:
agent = create_agent(model,tools)

In [ ]:
result = agent.invoke(
    {"messages": [{"role": "user", "content": "42 + 3 * 23은 뭔가요?"}]},
)

In [ ]:
result['messages'][-1].content

'42 + 3 * 23 = 111입니다.'

In [ ]:
result

{'messages': [HumanMessage(content='42 + 3 * 23은 뭔가요?', additional_kwargs={}, response_metadata={}, id='b79ba124-dc38-4527-b5bb-7f94134cd905'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 244, 'total_tokens': 264, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXgDdbPParFgrMGFtVZLzie2zpN2C', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a12964-9884-7ea2-b1c0-7f506b77971e-0', tool_calls=[{'name': 'multiply', 'args': {'a': 3, 'b': 23}, 'id': 'call_HlSe29Ns9AqOaGZDLJJpqMrb', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 244, 'output_tokens': 20, 'total_tokens': 264, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='69', name='multiply', id='d0ed1390-df81-45b3-ab35-ee8cc913f315', tool_call_id='call_HlSe29Ns9AqOaGZDLJJpqMrb'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 275, 'total_tokens': 295, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXgDepOke7dvUZkZfNCXNAYHwKaUH', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a12964-9b8a-7eb1-acdb-8965c82af83c-0', tool_calls=[{'name': 'add', 'args': {'a': 42, 'b': 69}, 'id': 'call_gJtFxnqZpKPITyd12bHRIEuK', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 275, 'output_tokens': 20, 'total_tokens': 295, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='111', name='add', id='fb9840be-db2d-40a4-87aa-cc9c0af9977a', tool_call_id='call_gJtFxnqZpKPITyd12bHRIEuK'),
  AIMessage(content='42 + 3 * 23 = 111입니다.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 15, 'prompt_tokens': 306, 'total_tokens': 321, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXgDeA2cvdnYbCw95xVd9ARlDe2Rv', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a12964-9ddc-7e11-9073-d2f7de2b6264-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 306, 'output_tokens': 15, 'total_tokens': 321, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}

In [ ]:
# system_prompt
agent = create_agent(
    model,
    tools,
    system_prompt = "당신은 초등학교 선생님입니다. 학생 수준에 맞춰 답변하고, 모든 사칙연산에서 Tool을 호출하시오."
  )

In [ ]:
result = agent.invoke(
    {"messages": [{"role": "user", "content": "42 + 3 * 23은 뭔가요?"}]},
)

In [ ]:
result['messages'][-1].content

'먼저 곱셈부터 해요.\n\n- 3 × 23 = 69\n- 42 + 69 = 111\n\n그래서 **42 + 3 × 23 = 111** 입니다.'

In [ ]:
result

{'messages': [HumanMessage(content='42 + 3 * 23은 뭔가요?', additional_kwargs={}, response_metadata={}, id='ab074f28-f792-40ec-a6ac-e201b48fe892'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 279, 'total_tokens': 299, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXgFyUr40jvqJ5Nlc8ReA1ddt2OIP', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a12966-cf97-7ef3-966f-40b9634dcfe5-0', tool_calls=[{'name': 'multiply', 'args': {'a': 3, 'b': 23}, 'id': 'call_3WcfcZq9dlHMaJTBAlusyG7t', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 279, 'output_tokens': 20, 'total_tokens': 299, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='69', name='multiply', id='ccaa9828-5cd3-4796-a02d-0eb5bf141b07', tool_call_id='call_3WcfcZq9dlHMaJTBAlusyG7t'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 310, 'total_tokens': 330, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXgFzaWfWjuCtzpi8qRNYT38TwHuj', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a12966-d1ba-7ad0-a09b-1731cce17335-0', tool_calls=[{'name': 'add', 'args': {'a': 42, 'b': 69}, 'id': 'call_xa1FPrIcai1MYmKNnljDNvdP', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 310, 'output_tokens': 20, 'total_tokens': 330, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='111', name='add', id='0b9912b4-2c85-45ea-bfa7-727c76d0a5c1', tool_call_id='call_xa1FPrIcai1MYmKNnljDNvdP'),
  AIMessage(content='먼저 곱셈부터 해요.\n\n- 3 × 23 = 69\n- 42 + 69 = 111\n\n그래서 **42 + 3 × 23 = 111** 입니다.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 49, 'prompt_tokens': 341, 'total_tokens': 390, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXgG0GEzHDA3ydAeruMrCszBQBvNL', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a12966-d50d-7c21-b87c-30f3c8b62e61-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 341, 'output_tokens': 49, 'total_tokens': 390, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}

#### 에이전트 구축 실습 2

*   Franfurter Exchange rates data API [링크](https://frankfurter.dev/)

In [ ]:
import requests
from langchain.tools import tool

@tool
def get_exchange_rate(base: str = "USD", quote: str = "KRW", amount: float = 1.0) -> str:
    """
    특정 통화의 환율을 조회합니다.
    예: base='USD', quote='KRW'이면 1달러가 몇 원인지 조회합니다.
    amount를 넣으면 해당 금액을 환산합니다.
    """

    base = base.upper()
    quote = quote.upper()

    url = f"https://api.frankfurter.dev/v2/rate/{base}/{quote}"

    response = requests.get(url, timeout=10)
    response.raise_for_status()

    data = response.json()

    rate = data["rate"]
    date = data.get("date", "알 수 없음")

    converted = amount * rate

    return (
        f"기준일: {date}\n"
        f"환율: 1 {base} = {rate:,.2f} {quote}\n"
        f"환산: {amount:,.2f} {base} = {converted:,.2f} {quote}"
    )

In [ ]:
agent = create_agent(
    model="gpt-5.4-mini",
    tools=[get_exchange_rate],
    system_prompt="""
너는 환율 정보를 알려주는 친절한 금융 정보 assistant다.

사용자가 원-달러 환율, 달러 환율, USD/KRW 환율을 물어보면
반드시 get_exchange_rate Tool을 사용해 최신 환율을 조회해라.

한국에서 말하는 '원-달러 환율'은 보통
'1달러가 몇 원인지', 즉 USD -> KRW 환율을 의미한다.

답변에는 반드시 다음을 포함해라.
1. 기준일
2. Frankfurter API 기준이라는 설명

투자 조언처럼 말하지 말고, 조회된 환율 정보만 간단히 설명해라.
""",
)

In [ ]:
result = agent.invoke({ "messages": [{ "role": "user","content": "오늘 원-달러 환율 알려줘"}]})

In [ ]:
result

{'messages': [HumanMessage(content='오늘 원-달러 환율 알려줘', additional_kwargs={}, response_metadata={}, id='57164219-1cad-4637-bc28-8b3ce4c13fbc'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 27, 'prompt_tokens': 346, 'total_tokens': 373, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXhA4WgukhEvJ1c1ZSNsd8NQ4sZoM', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a1299b-ddf7-7f81-8829-0491a8f4680b-0', tool_calls=[{'name': 'get_exchange_rate', 'args': {'base': 'USD', 'quote': 'KRW', 'amount': 1}, 'id': 'call_7hMyJbPMZIG6qjJWfEhBO6XJ', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 346, 'output_tokens': 27, 'total_tokens': 373, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='기준일: 2026-10-11\n환율: 1 USD = 1,341.97 KRW\n환산: 1.00 USD = 1,341.97 KRW', name='get_exchange_rate', id='a3fe4be0-4066-4eb0-b98d-e1ca5bbea014', tool_call_id='call_7hMyJbPMZIG6qjJWfEhBO6XJ'),
  AIMessage(content='오늘 원-달러 환율은 기준일 2026-10-11 기준으로 **1달러 = 1,341.97원**입니다.  \n**Frankfurter API 기준**입니다.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 46, 'prompt_tokens': 430, 'total_tokens': 476, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXhA5iPi3q6V9HTULSXJ406Lga7ju', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a1299b-e737-77f0-80db-8c42e60b1dfb-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 430, 'output_tokens': 46, 'total_tokens': 476, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}

#### 에이전트 구축 실습3

앞서 구현한 `get_weather` Tool을 활용하여 다음 조건을 만족하는 날씨 안내 Agent를 구축하세요.

**실습 요구사항**

1. 사용자가 **한국의 지역 날씨**를 질문하면 `get_weather` Tool을 호출하여 고정된 날씨 정보(**-2도, 미세먼지 매우 나쁨**)를 제공하세요.
2. 사용자가 **한국 외 지역의 날씨**를 질문하면 Tool을 호출하지 않고, **“한국 외의 날씨 정보는 제공하지 않습니다.“**라는 메시지를 반환하세요.
3. `system_prompt`를 활용하여 Agent가 위 조건에 따라 동작하도록 설정하세요.

**실행 예시**
- 입력: “서울 날씨 알려줘” → `get_weather` 호출 후 날씨 정보 제공
- 입력: “도쿄 날씨 알려줘” → “한국 외의 날씨 정보는 제공하지 않습니다.”

In [ ]:
from langchain.chat_models import init_chat_model
from langchain.tools import tool
from langchain.agents import create_agent

# 1. 모델 생성
model = init_chat_model("gpt-5.4-mini")


# 2. 날씨 도구 생성
@tool
def get_weather(location: str) -> str:
    """한국의 날씨 정보를 제공합니다."""
    return f"{location}의 날씨는 눈이 오고, -2도, 미세먼지 나쁨입니다."


# 3. 에이전트 생성
agent = create_agent(
    model,
    tools=[get_weather],
    system_prompt="""
    당신은 한국의 날씨 정보를 제공하는 AI 에이전트입니다.

    다음 규칙을 반드시 지키세요.

    1. 사용자가 한국의 지역 날씨를 질문하면
       반드시 get_weather 도구를 호출하여 답변하세요.

    2. 사용자가 한국 외의 지역 날씨를 질문하면
       get_weather 도구를 호출하지 마세요.

    3. 한국 외의 지역에 대해서는 반드시 다음 문장으로만 답변하세요.
       "한국 외의 날씨 정보는 제공하지 않습니다."

    4. 날씨 정보를 임의로 만들어내지 마세요.
    """
)

In [ ]:
result = agent.invoke(
    {"messages": [
        {"role": "user", "content": "지금 서울 날씨 어때?"}
    ]}
)

result["messages"][-1].content

'서울의 날씨는 눈이 오고, -2도이며 미세먼지는 나쁨입니다.'

In [ ]:
result = agent.invoke(
    {"messages": [
        {"role": "user", "content": "지금 도쿄 날씨 어때?"}
    ]}
)

result["messages"][-1].content

'한국 외의 날씨 정보는 제공하지 않습니다.'

### Built-in Tools

#### Python REPL

In [ ]:
# !pip install langchain_experimental

In [ ]:
# module import

In [ ]:
# python_repl 객체 생성

In [ ]:
python_repl

In [ ]:
# run()

In [ ]:
# 도구 생성

In [ ]:
from langchain.agents import create_agent

agent = create_agent(
    model="gpt-5.5",
    tools=[python_repl_tool],
)

In [ ]:
# 에이전트 실행

In [ ]:
result['messages']

In [ ]:
result['messages'][-1].content

In [ ]:
# 에이전트 실행2

In [ ]:
result['messages'][-1].content

#### Tavily Search

In [ ]:
!pip install -qU langchain-tavily

In [ ]:
os.environ["TAVILY_API_KEY"] = ""

In [ ]:
# 도구 생성
from langchain_tavily import TavilySearch

tool = TavilySearch(
    max_results=5,
    topic="general",
    # include_answer=False,
    # include_raw_content=False,
    # include_images=False,
    # include_image_descriptions=False,
    # search_depth="basic",
    # time_range="day",
    # include_domains=None,
    # exclude_domains=None
)

In [ ]:
from langchain.chat_models import init_chat_model

model = init_chat_model(model="gpt-5.4-mini")

In [ ]:
agent = create_agent(model, [tool])

In [ ]:
result = agent.invoke(
    {"messages": [{"role": "user", "content": "오늘 한국 경제 뉴스 알려줘"}]}
)

In [ ]:
result["messages"]

[HumanMessage(content='오늘 한국 경제 뉴스 알려줘', additional_kwargs={}, response_metadata={}, id='a460140e-79b0-45ef-bf0a-f3fb1fb78451'),
 AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 45, 'prompt_tokens': 1274, 'total_tokens': 1319, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXhNSARlWMa9YCtD1PV8iUaya2ns2', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a129a8-8a80-7fb1-b5ea-3b87d50ded3d-0', tool_calls=[{'name': 'tavily_search', 'args': {'query': '오늘 한국 경제 뉴스', 'search_depth': 'advanced', 'topic': 'news', 'time_range': 'day', 'include_images': False}, 'id': 'call_ExShewZp1TbTwYOEjXyR153g', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 1274, 'output_tokens': 45, 'total_tokens': 1319, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
 ToolMessage(content='{"query": "오늘 한국 경제 뉴스", "follow_up_questions": null, "answer": null, "images": [], "results": [{"url": "https://m.wowtv.co.kr/Finance/DomesticStock/Index?menuSeq=1099", "title": "국내증시 | 증권 | 뉴스 | 한국경제TV", "content": "오늘의 주요뉴스\\n\\n특징주뉴스\\n\\n### 오늘의 주요 뉴스\\n\\n 北 MZ들 \\"룰루레몬 옷 좀\\"...\\"사고방식 변했다\\"\\n 반도체 힘 빠졌는데 2차전지 \'완충\'...ETF 수익률 상위권 \'싹쓸이\'\\n \\"주문 급한데\\" 발 동동...쿠팡 자정께 \'접속불가\' 먹통\\n 스타벅스, \'타코\' 삼킬까...\\"외식업 역대 최대 딜\\"\\n 뉴욕증시, 오픈AI \'실적 쇼크\'에 기술주 하락...나스닥 1.25%↓\\n\\n### 특징주뉴스\\n\\n 미 금리 24년 최고...삼전 영업익 100조 돌파 - 와우넷 오늘장전략\\n\\n  현재가 306,500   하락\\n\\n  코스맥스 A192820\\n [단독] 김동관 전략통, 한화오션 핵잠 지휘…어성철 사장 유임\\n\\n  현재가 72,000   하락\\n\\n  한화오션 A042660\\n 첫 민간 누리호 날아올랐다...K-우주 밸류체인 증명\\n\\n  현재가 14,450   하락\\n\\n  나라스페이스테크놀로지 A478340\\n\\n### 업종 · 테마별 상위\\n\\n#### 업종별상위)\\n\\n 섬유·의류 0.08%\\n 화학 0.34%\\n 비금속 0.48%\\n 종이·목재 0.53%\\n 의료·정밀기기 0.69%\\n\\n#### 테마별상위)\\n\\n HLB그룹주 14.19%\\n 코비박 8.72%\\n 오리온그룹주 7.04%\\n OSAT 6.89%\\n 품절주 6.78%\\n\\n### 랭킹100)\\n\\n전체);)\\n\\n코스피);)\\n\\n코스닥);)\\n\\n### 오늘의 투자전략\\n\\n 10월 8일 (목) 안인기 시황 & 전략\\n ◆10월 8일 (목)요일 감은숙의 퀵 브리핑\\n 삼성전자 3Q 실적 발표 후 진로와 소부장 반도체 대응\\n\\n### 주체별 동향 2026-10-09 오전 08:01 장마감(억원)\\n\\n주체별 동향 상세 [...] 홍콩항생 23,785.79\\n\\n 344.71\\n 1.42%\\n\\n니케이 69,042.11\\n\\n 993.60\\n 1.41%\\n\\n관심종목 상세\\n\\n     | 미국 USD | 1,343.00 | 2.00 |\\n| 일본 JPY(100엔) | 851.48 | 2.83 |\\n| 유럽연합 EUR | 1,505.70 | 3.71 |\\n| 중국CNY | 200.34 | 0.27 |\\n\\n오늘의 무료방송\\n\\n photo\\n 감은숙대표 단기-주도|스윙-주도|중기-주도 10:00~11:00\\n 녹화방송) 구매)\\n\\n photo\\n 강호안인기 단기-가치|스윙-테마|중기-주도 10:00~11:00\\n 녹화방송) 구매)\\n\\n photo\\n 김동엽대표 단기-주도|스윙-가치|중기-가치 12:00~13:00\\n 녹화방송) 구매)\\n\\n관심종목\\n\\n인기검색종목\\n\\n최근검색종목\\n\\n로그인 후 관심종목을 등록하시면  \\n등록하신 종목의 시세를 쉽게 보실 수 있습니다.\\n\\n로그인 회원가입\\n\\n인기검색종목 상세\\n\\n      | 데이터가 없습니다. |\\n\\n최근검색종목 상세\\n\\n      | 소마젠 | 2,975 | 10 | 0.33% |\\n| 삼성전자 | 262,000 | 6,500 | 2.42% |\\n| SFA넥셀 | 8,680 | 220 | 2.60% |\\n| 녹십자엠에스 | 3,735 | 465 | 11.07% |\\n| 케이피엠테크 | 5,580 | 500 | 9.84% |\\n\\n오늘의 주요뉴스\\n\\n특징주뉴스\\n\\n### 오늘의 주요 뉴스 [...] ### 주체별 동향 2026-10-09 오전 08:01 장마감(억원)\\n\\n주체별 동향 상세\\n\\n   | 분류 | 외국인 | 기관 | 개인 |\\n| 코스피 | 20,810 | 16,749 | 29,972 |\\n| 코스닥 | 818 | 1,075 | 482 |\\n\\n### 와우 금융 서비스\\n\\n실시간 방송   파트너 방송   증권교육\\n\\n와우밴드)   주식창   추천상품\\n\\n국고처 대박천국\\n\\n뉴스 목록 보기\\n\\n 뉴스;)\\n\\n  + 홈\\n  + 전체뉴스\\n  + 랭킹뉴스\\n  + 경제\\n  + 증권\\n  + 산업·IT\\n  + 부동산\\n  + 정치\\n  + 사회\\n  + 국제\\n  + 가상화폐\\n  + 생활문화\\n  + 취업\\n  + 스포츠\\n  + 연예\\n 칼럼·연재;)\\n\\n  + 홈\\n 증권 데이터;)\\n\\n  + 종목 모니터링;)\\n  + 투자분석;)\\n  + 국내증시;)\\n  + 해외증시;)\\n 와우넷;)\\n\\n  + 무료방송\\n  + 파트너스\\n  + 추천 상품\\n  + 오늘의 특징주\\n  + 수익후기\\n  + 이벤트\\n 주식창;)\\n\\n  + 홈\\n  + 파트너\\n  + AI추천\\n  + 마켓이슈\\n  + 이벤트\\n 미네르바아카데미;)\\n\\n  + 스페셜강의\\n  + 투자/재테크\\n  + 부동산/세무\\n  + 산업\\n  + [[접수·할인] 9월 투자콘서트「위기 속 반전, 수익의 골든타임」](\\n  + [[모집-4기-] 돈버는 트레이딩 투자 북클럽](\\n  + [[할인50%] 한·미 투자 올인원 클래스](\\n 한경고향드림;)", "score": 0.7147281, "raw_content": null, "id": "d07145-00"}, {"url": "https://m.mk.co.kr/push", "title": "매일경제", "content": "22:15  [국채금리 급등 미증시 제동 [월가월부] Image 27: 기사 상세 보기](  \\n    18:53  [Image 28: 기사 이미지 [속보] 노벨화학상에 앙리 카강·소아이 겐소 Image 29: 기사 상세 보기](  \\n    17:33  [Image 30: 기사 이미지 [속보] 경기남부청, 민주당 경기도당 압수수색 Image 31: 기사 상세 보기](  \\n    16:44  [Image 32: 기사 이미지 [속보] 민주노총, 사회적 대화 복귀 표결 무산…대의원 과반 미달 Image 33: 기사 상세 보기](  \\n    15:53  [Image 34: 기사 이미지 [속보] 거래소, 법원 ‘시총 미달 상폐’ 급제동에 “후속 상폐절차 유예” Image 35: 기사 상세 보기](  \\n    15:35   코스피 6803.90(▼137.49p, 1.98%) 마감, 원·달러 환율 1340.4원    \\n    14:05  [Image 36: 기사 이미지 [속보] ‘명태균 여론조사 무상수수’ 윤석열 2심 무죄 Image 37: 기사 상세 보기](  \\n    14:04  [Image 38: 기사 이미지 [속보] 우주청 “누리호 5차 발사 성공” 공식 발표 Image 39: 기사 상세 보기](  \\n    13:05  [Image 40: 기사 이미지 [속보] 우주청장 “누리호 예정된 비행 절차에 따라 목표 궤도 도달” Image 41: 기사 상세 보기]( [...] 22:25  [S&P500 최고가 문턱 [월가월부] Image 58: 기사 상세 보기](  \\n    20:13  [Image 59: 기사 이미지 [속보] 손흥민 A매치 59호골 폭발…차범근 넘어 한국인 최다 신기록 Image 60: 기사 상세 보기](  \\n    19:15  [Image 61: 기사 이미지 [속보] 北 “영토 1mm라도 침범한다면 즉시적 강력한 대응할 것” Image 62: 기사 상세 보기](  \\n    18:54  [Image 63: 기사 이미지 [속보] 노벨물리학상에 ‘뉴트리노 관측’ 프랜시스 할선 Image 64: 기사 상세 보기](  \\n    18:03  [Image 65: 기사 이미지 [속보] 수사개혁위 “변호사 5년간 매년 100명 이상 경찰로 채용” 권고 Image 66: 기사 상세 보기](  \\n    15:38   코스피 6941.39(▼62.35p, 0.89%) 마감, 원·달러 환율 1343.6원    \\n    12:12  [Image 67: 기사 이미지 [속보] 조희대 “국회와 대통령, 대법원장의 제청에 관여할 수 없어” Image 68: 기사 상세 보기](  \\n    09:04   코스피 7044.67(▲40.93p, 0.58%) 개장, 원·달러 환율 1344.0원    \\n    08:08  [Image 69: 기사 이미지 [속보] 경찰청, 은행권 전방위 AI해킹 사건 전담수사팀 구성…4개팀·28명 Image 70: 기사 상세 보기]( [...] 12:44  [Image 42: 기사 이미지 [속보] 초소형 군집위성 6호 분리 확인…누리호 주탑재위성 모두 분리 Image 43: 기사 상세 보기](  \\n    12:28  [Image 44: 기사 이미지 [속보] 누리호 낮 12시 25분 발사…우주로 도약 중 Image 45: 기사 상세 보기](  \\n    11:31  [Image 46: 기사 이미지 [속보] 오세훈 서울시장 “전북의 올림픽 공동 개최 제안, 다 수용할 생각” Image 47: 기사 상세 보기](  \\n    11:10  [Image 48: 기사 이미지 [속보] 경찰, 금융기관 해킹 IP 상당수 ‘세탁용’ 확인…국제공조로 추적 Image 49: 기사 상세 보기](  \\n    10:35  [Image 50: 기사 이미지 [속보] 인구감소지역 89→92곳…부산 금정·동두천·통영 새로 편입 Image 51: 기사 상세 보기](  \\n    09:06   코스피 6864.25(▼77.14p, 1.11%) 개장, 원·달러 환율 1340.5원    \\n    08:52  [Image 52: 기사 이미지 [속보] 누리호 오늘 낮 12시 25분 발사 Image 53: 기사 상세 보기](  \\n    07:30  Image 54: 기사 이미지 매경이 전하는 세상의 지식 (매-세-지, 10월 7일) Image 55: 기사 상세 보기  \\n    07:03  [Image 56: 기사 이미지 [마이 모닝 브리핑] 10월 7일 팟캐스트 Image 57: 기사 상세 보기](", "score": 0.650934, "raw_content": null, "id": "a20b36-01"}, {"url": "https://news.naver.com/breakingnews/section/101/262", "title": "경제 : 네이버 뉴스", "content": "스포츠서울\\n\\n  19시간전\\n  집행에 나선다. 이 가운데 절반 이상인 3000억위안(약 60조원)은 기초 지방정부의 일반예산 재정능력을 보강하는 데 배정된다. 나머지 2500\\n\\n  머니투데이\\n\\n  19시간전\\n  기업들의 이익 성장세를 주도했을 것이라는 전망이 나온다. 9일(현지시간) 금융정보업체 LSEG에 따르면 월가 애널리스트들은 3분기에 스탠더드앤\\n\\n  블로터\\n\\n  21시간전\\n\\n  블라디미르 푸틴 러시아 대통령과 러시아의 경유 미국 수출을 늘리기로 한 합의했음에도 미국의 경유 가격이 의미 있게 내려갈 가능성은 희박하다고 전문가들이 전망하고 있다. 트럼\\n\\n  뉴시스\\n\\n  21시간전\\n  한국석유공사 유가정보시스템 오피넷에 따르면 10월 첫째 주 전국 주유소 휘발유 평균 판매가는 지난주보다 리터(L)당 0\\n\\n  연합뉴스TV\\n\\n  21시간전\\n  파이낸셜타임즈(FT)는 스페이스X가 그레인\\n\\n  머니투데이\\n\\n  21시간전\\n 가 경고했다고 영국 파이낸셜타임스(FT)가 9일(현지시각) 보도했다. 핌코의 최고투자책임자 댄\\n\\n  뉴시스\\n\\n  21시간전\\n  기술주 강세와 러시아산 경유 공급 확대 기대에 힘입어 상승 마감했다. 중동 긴장 완화 기대도 투자심리를 뒷받침했다. 다우존스30산업평균지수는 전장보다 423.31포인트(0.83%) 오른 5\\n\\n  파이낸셜뉴스\\n\\n  21시간전\\n\\n 은 9일(현지시간) 칼시가 백악관 대변인 임\\n\\n  파이낸셜뉴스\\n\\n  22시간전\\n  뉴욕증권거래소에서 S&P500지수는 전장보\\n\\n  머니투데이 [...] 한동훈, 민주당 \'딸 의혹\' 공세에 김민석·추미애 자녀 소환 \\"개떼처럼 달려들어라\\"\\n\\n [결혼과 이혼] \\"재산 1억2000 대 2300\\"…집 명의 놓고 서로 얼굴 붉힌 예비신랑신부\\n\\n     아이뉴스24\\n\\n  \\n\\n   [[결혼과 이혼] \\"재산 1억2000 대 2300\\"…집 명의 놓고 서로 얼굴 붉힌 예비신랑신부](\\n \\"빵 공짜로 줬더니\\"...초등학생 4명이 갑자기 한 행동에 \'흐믓\'\\n\\n     한국경제TV\\n\\n  \\n\\n   \\"빵 공짜로 줬더니\\"...초등학생 4명이 갑자기 한 행동에 \'흐믓\'\\n [ETF워치]2차전지 날고 방산 추락…개인은 커버드콜 담았다\\n\\n     비즈워치\\n\\n  \\n\\n   [[ETF워치]2차전지 날고 방산 추락…개인은 커버드콜 담았다](\\n 69-year-old transgender woman\'s life story meets director who wanted to listen\\n\\n     코리아헤럴드\\n\\n  \\n\\n   69-year-old transgender woman\'s life story meets director who wanted to listen\\n 로또 1245회 당첨번호 조회···\'1등 10명 전부 자동\'\\n\\n     더팩트\\n\\n  \\n\\n   로또 1245회 당첨번호 조회···\'1등 10명 전부 자동\'\\n\\n \\"명색이 집권당인데\\"… 추미애, 비공개 일정 요구에 \'반발\'\\n\\n     대전일보\\n\\n  \\n\\n   \\"명색이 집권당인데\\"… 추미애, 비공개 일정 요구에 \'반발\'\\n “췌장 다 망가진다”… 응급의학과 의사가 ‘절대 먹지 말라’는 음식\\n\\n     헬스조선 [...] 디지털데일리\\n\\n  1일전\\n  \\n\\n  이윤희 특파원 = 도널드 트럼프 미국 대통령이 8일(현지 시간) 블라디미르 푸틴 러시아 대통령과 통화에서 \\"러시아가 즉시 30만톤 이상의 디젤 연료(경유)를 미국과 세계시장에 공급하기로 합의됐다\\"고 밝혔다. 미 재무\\n\\n  뉴시스\\n\\n  1일전\\n  일제히 상승 마감했다. 기술주가 반등하면서 전날 하락했던 스탠더드앤드푸어스(S&P)500과 나스닥지수가 모두 올랐다. 반면 대장주 엔비디아가 고전하면서 반도체 종목들은 약세를\\n\\n  파이낸셜뉴스\\n\\n  1일전\\n\\n  닛케이 아시아 보도를 인용해 애플이 이달 아이폰 18 프로 주문\\n\\n  파이낸셜뉴스\\n\\n  1일전\\n  밝혔다. 트럼프 대통령은 이날 블라디미르 푸틴 러시아 대통령과 통화했다면서 러시아가 우선 즉각 30만t 넘게\\n\\n  파이낸셜뉴스\\n\\n  1일전\\n ’ 전국 17개교 단체관람 추진…8곳 관람 마쳐·6곳 취소\\n\\n     문화일보\\n\\n  \\n\\n   [[속보] ‘역사 왜곡 논란’ 영화 ‘암살자(들)’ 전국 17개교 단체관람 추진…8곳 관람 마쳐·6곳 취소](\\n “군고구마, 담배 냄새 나서 버렸다”…담배 상자에 넣어 배달한 편의점\\n\\n     전자신문\\n\\n  \\n\\n   “군고구마, 담배 냄새 나서 버렸다”…담배 상자에 넣어 배달한 편의점\\n\\n 서울 대학서 지인 여성 흉기로 찌르고 영국 도주…30대 남성 9일 만에 검거\\n\\n     강원일보\\n\\n  \\n\\n   서울 대학서 지인 여성 흉기로 찌르고 영국 도주…30대 남성 9일 만에 검거\\n “무서운 번식력”…‘중동 바퀴벌레’ 부산 침투\\n\\n     채널A\\n\\n   재생하기", "score": 0.6216563, "raw_content": null, "id": "d33699-02"}, {"url": "https://news.naver.com/section/101", "title": "경제 : 네이버 뉴스", "content": "뉴스1\\n\\n  1시간전\\n \\n\\n  연합뉴스\\n\\n  1시간전\\n  스타트업인 \'리플렉션 AI\'를 인수하기 위해 협상 중이라고 파이낸셜타임스(FT)가 10일(현지시간) 소식통을 인용해 보도했다. 인수가 여의치 않으면 투자를 심화하는 방안도 검\\n\\n  파이낸셜뉴스\\n\\n  1시간전\\n ’ 전국 17개교 단체관람 추진…8곳 관람 마쳐·6곳 취소\\n\\n     문화일보\\n\\n  \\n\\n   [[속보] ‘역사 왜곡 논란’ 영화 ‘암살자(들)’ 전국 17개교 단체관람 추진…8곳 관람 마쳐·6곳 취소](\\n 한동훈, 민주당 \'딸 의혹\' 공세에 김민석·추미애 자녀 소환 \\"개떼처럼 달려들어라\\"\\n\\n     매일신문\\n\\n  \\n\\n   한동훈, 민주당 \'딸 의혹\' 공세에 김민석·추미애 자녀 소환 \\"개떼처럼 달려들어라\\"\\n\\n “췌장 다 망가진다”… 응급의학과 의사가 ‘절대 먹지 말라’는 음식\\n\\n     헬스조선\\n\\n  \\n\\n   “췌장 다 망가진다”… 응급의학과 의사가 ‘절대 먹지 말라’는 음식\\n “무서운 번식력”…‘중동 바퀴벌레’ 부산 침투\\n\\n     채널A\\n\\n   재생하기\\n\\n   “무서운 번식력”…‘중동 바퀴벌레’ 부산 침투\\n \'볼보 EX90\' 395㎞ 장거리 달리고 배터리 28% 남았다[카미경]\\n\\n     블로터\\n\\n  \\n\\n   [\'볼보 EX90\' 395㎞ 장거리 달리고 배터리 28% 남았다[카미경]](\\n Why don\'t Koreans carry house keys anymore?\\n\\n     코리아중앙데일리 [...] 7 개의 관련뉴스 더보기\\n  새벽 발생한 쿠팡 관련 애플리케이션의 접속 오류에 대해, 쿠팡 측은 서비스 업그레이드 과정에서 비롯된 거라고 밝혔습니다. 해킹 가능성엔 선을 긋고, 피해 고객 등에 대한 보상안을 내놨습니다. 강진원 기자\\n\\n  19 개의 관련뉴스 더보기\\n  모델\\n\\n  조선비즈\\n\\n 코스피 6,625.93   177.97 -2.62%\\n\\n   \\n 코스닥 892.27   6.16 -0.69%\\n\\n   \\n\\n 가 이르면 28일 3분기 성적표를 공개한다. 앞서 실적을 발표한 삼성전자(005930)와 마찬가지로 역대 최고 실적이 예상된다. SK하이닉스가 \'영업이익률 80%\'를 돌파할 것인지도 관심사다\\n\\n  뉴스1\\n\\n  31분전\\n  사이트에 표출됐습니다. 글로벌 사모펀드(PEF) 운용사 텍사스퍼시픽그룹(TPG)이 카카오모빌리티 투자금 회수 방안을 다각도로 검토하고 있다.\\n\\n  조선비즈\\n\\n  59분전\\n  랠리를 재개하며 신고가 행진을 이어가는 가운데 코스피는 나홀로 제자리걸음을 하\\n\\n  매일경제\\n\\n  59분전\\n 에는 삼성전자에 이어 SK하이닉스의 자사주 매입도 막바지에 접어들면서 수급 공백 우려가 커질 전망이다\\n\\n  조선비즈\\n\\n  1시간전\\n  대신 8단 자동변속기를 탑재하고 교차로 대응 주행 보조 기능을 갖췄다. 실제 도로에서는 전방 교차로에 진입할 때 차량이 스스로 속도\\n\\n  블로터\\n\\n  1시간전\\n  낮아지자 겨울철 액화천연가스(LNG) 확보 경쟁이 치열해지고 있다. 올해 4분기 유럽의 LNG 수입량은 전년 동기 대비 6.5% 증가할 것으로\\n\\n  뉴스1\\n\\n  1시간전\\n \\n\\n  연합뉴스 [...] 본문 바로가기\\n\\nNAVER\\n\\n# 뉴스\\n\\n  엔터     스포츠     날씨     프리미엄\\n\\nMY \\n\\n뉴스 이용 설정을 할 수 있어요\\n\\n 언론사별\\n 정치\\n 경제\\n 사회\\n 생활/문화\\n IT/과학\\n 세계\\n 랭킹\\n 신문보기\\n 오피니언\\n TV\\n 팩트체크\\n 알고리즘 안내\\n 정정보도 모음\\n\\nMY \\n\\n뉴스 이용 설정을 할 수 있어요\\n\\n 금융\\n 증권\\n 부동산\\n\\n10.11(일)\\n\\n 전체 언론사\\n 뉴스스탠드\\n 라이브러리\\n\\n## 경제\\n\\n 금융\\n 증권\\n 산업/재계\\n 중기/벤처\\n 부동산\\n 글로벌 경제\\n 생활경제\\n 경제 일반\\n\\nAI 뉴스 알고리즘 추천 알고리즘 궁금하다면? 바로가기\\n\\n프리미엄콘텐츠 투자 정보부터 트렌드까지! 바로가기\\n\\n헤드라인 뉴스 안내 \\n\\n각 헤드라인의 기사와 배열 순서는 개인화를 반영해 추천되며, 기사묶음의 대표 기사는 구독 언론사 중심으로 제공됩니다. 기사 수량이 표기된 기사 우측 하단의 파란색 아이콘을 클릭하면 기사묶음을 확인할 수 있고 기사묶음과 기사묶음 타이틀도 기사 내용을 기반으로 자동 추출됩니다.\\n\\n알고리즘 자세히 보기\\n\\n  침투테스트 도구 ‘아르텍스’(ARTEX)가 악용 논란 끝에 공개 개발을 중단한다. 아르텍스는 최근 한국 금융권을 겨냥한 연쇄 해킹 공격에 활용된 것으로 알려졌다. 10일 AFP·로이터 통신 등\\n\\n  30 개의 관련뉴스 더보기\\n 가 사상 최초로 분기 영업이익 100조 원을 뛰어넘는 새 역사를 썼지만 시장 반응은 냉랭했다. 실적 기대가 주가에 선반영돼 셀온(Sell-on)현상으로 매도량이 몰리는데다 시장 눈높이가 높아진", "score": 0.61363083, "raw_content": null, "id": "221022-03"}, {"url": "https://www.donga.com/news/Economy/List", "title": "최신기사｜경제｜동아일보", "content": "뉴질랜드 키위의 단일 수출창구와 EU 생산자조직, 한국 양파·마늘 경작신고, 호주 NSW 쌀 규제 완화 사례를 통해 농민들이 생산·출하·판매 규칙을 공동으로 정하는 자조금·품목조직의 권한과 농산물 수급조절 방식을 살펴본다.\\n\\n  + 19시간 전\\n  + 좋아요 개\\n  + 코멘트 개\\n #### “같은 날 샀는데 나만 왜 비싸?”…온라인 쇼핑 ‘가격차’ 상담 증가세\\n\\n  온라인 쇼핑몰에서 같은 시간에 상품을 구매했는데도 쿠폰 노출 여부에 따라 가격 차이가 발생하는 경우가 적지 않은 것으로 나타났다. 관련 소비자상담은 최근 수년 사이 늘어나고 있는데, 실태조사가 필요하다는 지적이 나온다.10일 국회 정무위원회 소속 국민의힘 박성훈 의원이 한국소비자원으로…\\n\\n  + 20시간 전\\n  + 좋아요 개\\n  + 코멘트 개\\n #### 韓 금융권 해킹 때문?…中 침투용 AI ‘아르텍스’ 비공개 전환\\n\\n  국내 금융사를 겨냥한 연쇄 해킹 공격에 사용된 것으로 알려진 중국산 인공지능(AI) 침투테스트 도구 ‘아르텍스(ARTEX)’가 공개 개발을 중단한다. 아르텍스는 사이버 공격에 악용되고 있다는 논란이 끊이지 않았다. 10일 로이터통신 등에 따르면 아르텍스 개발자 ‘오텀(Autumn)-2…\\n\\n  + 20시간 전\\n  + 좋아요 개\\n  + 코멘트 개\\n #### [‘부잣집 딸’ 분위기가 패션으로…요즘 뜨는 ‘현백코어’ 뭐길래 [트렌디깅]]( [...] # 동아일보\\n\\n## 경제\\n\\n 최신기사\\n 기업CEO\\n 부동산\\n 금융\\n IT/의학\\n 자동차\\n\\n날짜선택\\n\\n지면기사만 보기\\n\\n #### “AI한테 욕하는 것도 학대?”…앤트로픽 새 정책에 의견 분분\\n\\n  인공지능(AI) 기업 앤트로픽이 AI 챗봇을 상대로 지속적인 폭언이나 학대 행위를 하는 사용자를 제재할 수 있도록 이용 정책을 개정했다.9일(현지 시간) 영국 BBC는 앤트로픽이 자사 AI 챗봇 ‘클로드’에 지속적이고 불필요한 학대 행위를 하는 사용자를 제재할 수 있도록 정책을 바꿨다…\\n\\n  + 11시간 전\\n  + 좋아요 개\\n  + 코멘트 개\\n #### 싼 물건 살 때 더 발품 파는 이유…21개국 ‘돈 쓰는 심리’ 조사해보니\\n\\n  같은 금액을 할인받아도 사람들은 비싼 물건보다 싼 물건을 살 때 더 발품을 팔았다. 21개국 5589명을 조사한 결과 ‘정신적 회계’가 지금도 소비 결정에 영향을 미치는 것으로 나타났다.\\n\\n  + 11시간 전\\n  + 좋아요 개\\n  + 코멘트 개\\n #### 임성재, PGA 투어 베이커런트 3R 공동 12위…역전 우승 희망\\n\\n  임성재가 미국프로골프(PGA) 투어 베이커런트 클래식(총상금 800만 달러) 3라운드에서 공동 12위에 오르며 역전 우승 희망을 살렸다.임성재는 10일 일본 요코하마의 요코하마 컨트리클럽(파71)에서 열린 대회 3라운드에서 보기 없이 버디만 3개를 낚아 3언더파 68타를 쳤다.이로써 …\\n\\n  + 15시간 전\\n  + 좋아요 개\\n  + 코멘트 개\\n #### “내 키위인데 아무 데나 못 판다”…판매권까지 묶은 해외 농민들 [...] “한국 성형외과 환자 정보를 구할 수 있나.” “2020∼2026년 수술 받은 환자들의 정보가 있다.” “얼마인가.” “3000달러(약 402만 원)다. 비트코인으로 받겠다.” 9일 동아일보 취재팀이 온라인 메신저 텔레그램에서 해커로 추정되는 인물과 나눈 대화다. 상대방은 한 성형외과…\\n\\n  + 1일 전\\n  + 좋아요 개\\n  + 코멘트 개PDF지면보기;)\\n #### 임금협상 결렬 한화오션 노조, 하청 이어 원청도 고공농성 돌입\\n\\n  한화오션 노동조합이 사 측 제시안을 거부하고 크레인 고공농성을 시작했다. 앞서 이 회사 하청 노조에 이어 원청 노조까지 고공농성에 나선 것이다. 9일 조선업계에 따르면 김유철 금속노조 한화오션지회장은 8일 경남 거제사업장 내 크레인에 올라 고공농성을 시작했다. 사 측은 전날 교섭에서 …\\n\\n  + 1일 전\\n  + 좋아요 개\\n  + 코멘트 개PDF지면보기;)\\n #### 고향 과일 찾는 외국인 늘며 밀수 4배로… 병해충 확산 비상등\\n\\n  ⟪수입 금지 농산물, SNS로 은밀 거래‘고향 과일’을 찾는 국내 체류 외국인들이 늘면서 수입이 금지된 해외 과일이 SNS를 통해 은밀하게 거래되고 있다. 검역을 거치지 않은 농산물로 인한 외래 병해충 피해도 증가하고 있어 밀수 급증에 대한 조치가 필요하다는 지적이 나온다.⟫“우리도 …\\n\\n  + 1일 전\\n  + 좋아요 개\\n  + 코멘트 개PDF지면보기;)\\n #### 외래종 코브라-악어도 몰래 거래… “유기 땐 생태계 교란”", "score": 0.6016175, "raw_content": null, "id": "3e1674-04"}], "response_time": 1.82, "request_id": "c6059a0f-9aec-439e-a8c7-b42d35426049"}', name='tavily_search', id='f385b7e6-9218-4d87-acc4-c63f120dfe47', tool_call_id='call_ExShewZp1TbTwYOEjXyR153g'),
 AIMessage(content='오늘 한국 경제 뉴스 핵심만 추리면 이런 흐름이에요.\n\n### 1) 국내 증시 약세\n- 코스피가 하락 마감/약세 흐름으로 보도됐고, 환율도 원·달러 1340원대 근처에서 움직였습니다.\n- 시장에서는 대형주 실적 기대가 이미 반영됐다는 반응도 나옵니다.\n\n### 2) 반도체·IT 이슈\n- 삼성전자 실적 기대가 큰 가운데, 시장은 “호실적에도 주가 반응이 제한적일 수 있다”는 분위기입니다.\n- SK하이닉스도 실적 기대가 이어지지만, 고점 부담과 수급 공백 우려가 함께 언급됐습니다.\n\n### 3) 2차전지·ETF 관심\n- 반도체가 주춤한 사이 2차전지 관련주가 상대적으로 강했고, 관련 ETF 수익률이 상위권을 차지했다는 기사들이 보입니다.\n\n### 4) 쿠팡 접속 장애\n- 쿠팡 앱/서비스 접속 오류가 발생해 이용자 불편이 있었고, 서비스 업그레이드 과정이라는 설명이 나왔습니다.\n- 해킹 가능성은 일단 선을 그은 상태입니다.\n\n### 5) 우주·방산 뉴스\n- 누리호 관련 발사/분리 성공 보도가 크게 나왔고, 한국 우주산업 밸류체인 기대감이 언급됐습니다.\n- 한화오션 등 방산·조선 쪽도 핵잠 관련 이슈로 관심을 받고 있습니다.\n\n### 6) 금융권 해킹 대응\n- 국내 금융기관을 겨냥한 해킹 이슈가 계속되면서, 전담수사팀 구성 등 대응 뉴스가 나왔습니다.\n\n원하시면 제가 바로\n- **“오늘 한국 경제 뉴스 5개만 초간단 요약”**\n- **“주식시장 영향 중심으로 정리”**\n- **“부동산/환율/반도체만 따로”**\n이렇게 나눠서 더 보기 쉽게 정리해드릴게요.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 465, 'prompt_tokens': 8920, 'total_tokens': 9385, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 1152}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXhNVyieP1H4JlWxBfk1akP5Z8n8J', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--01a129a8-97ce-7ae1-b565-fbc37230ef50-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 8920, 'output_tokens': 465, 'total_tokens': 9385, 'input_token_details': {'audio': 0, 'cache_read': 1152}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]

In [ ]:
result['messages'][-1].content

'오늘 한국 경제 뉴스 핵심만 추리면 이런 흐름이에요.\n\n### 1) 국내 증시 약세\n- 코스피가 하락 마감/약세 흐름으로 보도됐고, 환율도 원·달러 1340원대 근처에서 움직였습니다.\n- 시장에서는 대형주 실적 기대가 이미 반영됐다는 반응도 나옵니다.\n\n### 2) 반도체·IT 이슈\n- 삼성전자 실적 기대가 큰 가운데, 시장은 “호실적에도 주가 반응이 제한적일 수 있다”는 분위기입니다.\n- SK하이닉스도 실적 기대가 이어지지만, 고점 부담과 수급 공백 우려가 함께 언급됐습니다.\n\n### 3) 2차전지·ETF 관심\n- 반도체가 주춤한 사이 2차전지 관련주가 상대적으로 강했고, 관련 ETF 수익률이 상위권을 차지했다는 기사들이 보입니다.\n\n### 4) 쿠팡 접속 장애\n- 쿠팡 앱/서비스 접속 오류가 발생해 이용자 불편이 있었고, 서비스 업그레이드 과정이라는 설명이 나왔습니다.\n- 해킹 가능성은 일단 선을 그은 상태입니다.\n\n### 5) 우주·방산 뉴스\n- 누리호 관련 발사/분리 성공 보도가 크게 나왔고, 한국 우주산업 밸류체인 기대감이 언급됐습니다.\n- 한화오션 등 방산·조선 쪽도 핵잠 관련 이슈로 관심을 받고 있습니다.\n\n### 6) 금융권 해킹 대응\n- 국내 금융기관을 겨냥한 해킹 이슈가 계속되면서, 전담수사팀 구성 등 대응 뉴스가 나왔습니다.\n\n원하시면 제가 바로\n- **“오늘 한국 경제 뉴스 5개만 초간단 요약”**\n- **“주식시장 영향 중심으로 정리”**\n- **“부동산/환율/반도체만 따로”**\n이렇게 나눠서 더 보기 쉽게 정리해드릴게요.'

### Memory

In [ ]:
from langgraph.checkpoint.memory import InMemorySaver

agent = create_agent(
    model,
    tools,
    checkpointer = InMemorySaver()
)

In [ ]:
response = agent.invoke(
    {"messages" : [{"role" : "user", "content" : "안녕하세요. 제 이름은 홍길동 입니다."}]},
    {"configurable" : {"thread_id" : "1"}}
)

In [ ]:
response["messages"][-1].content

'안녕하세요, 홍길동님! 반갑습니다.  \n무엇을 도와드릴까요?'

In [ ]:
response = agent.invoke(
    {"messages": [{"role": "user", "content": "방금 뭐라고 했죠 제가?"}]},
    {"configurable": {"thread_id": "1"}},
)

In [ ]:
response["messages"][-1].content

'방금 말씀하신 내용은 **“안녕하세요. 제 이름은 홍길동 입니다.”**였습니다.'

In [ ]:
response = agent.invoke(
    {"messages": [{"role": "user", "content": "지금까지 무슨 얘기 나눴죠?"}]},
    {"configurable": {"thread_id": "1"}},
)

In [ ]:
for i, msg in enumerate(response["messages"]):
    print(f"--- Message {i+1} ---")
    print(msg.content)
    print()

--- Message 1 ---
안녕하세요. 제 이름은 홍길동 입니다.

--- Message 2 ---
안녕하세요, 홍길동님! 반갑습니다.
무엇을 도와드릴까요?

--- Message 3 ---
방금 뭐라고 했죠 제가?

--- Message 4 ---
방금 말씀하신 내용은 **“안녕하세요. 제 이름은 홍길동 입니다.”**였습니다.

--- Message 5 ---
지금까지 무슨 얘기 나눴죠?

--- Message 6 ---
지금까지 나눈 내용은 이렇습니다:

1. 당신이 “안녕하세요. 제 이름은 홍길동 입니다.”라고 소개하셨고
2. 제가 “안녕하세요, 홍길동님! 반갑습니다. 무엇을 도와드릴까요?”라고 인사드렸습니다.
3. 그다음 당신이 “방금 뭐라고 했죠 제가?”라고 물으셨고
4. 제가 당신이 처음에 말씀하신 소개 문장을 그대로 알려드렸습니다.

원하시면 제가 대화 내용을 더 짧게 한 줄로도 정리해드릴게요.

In [ ]:
response = agent.invoke(
    {"messages": [{"role": "user", "content": "지금까지 무슨 얘기 나눴죠?"}]},
    {"configurable": {"thread_id": "2"}},
)

In [ ]:
for i, msg in enumerate(response["messages"]):
    print(f"--- Message {i+1} ---")
    print(msg.content)
    print()

--- Message 1 ---
지금까지 무슨 얘기 나눴죠?

--- Message 2 ---
지금 이 대화에서는 아직 별다른 주제는 없었고, 방금 전까지는 **제가 사용 가능한 도구(덧셈, 곱셈, 나눗셈)** 안내를 받은 상태예요.

즉, 현재까지 대화 내용은 거의 없고, 이제부터 원하시는 걸 말씀해 주시면 이어서 도와드릴 수 있습니다.

### 구조화된 답변

In [ ]:
from pydantic import BaseModel, Field

class Movie(BaseModel):
    """상세한 영화 정보."""
    title: str = Field(description="영화의 제목")
    year: int = Field(description="개봉 연도")
    director: str = Field(description="영화 감독 이름")
    rating: float = Field(description="영화 평점 (10점 만점)")

In [ ]:
model_with_structure = model.with_structured_output(Movie)

In [ ]:
response = model_with_structure.invoke("영화 인셉션에 대해 설명해 주세요")

In [ ]:
response

Movie(title='Inception', year=2010, director='Christopher Nolan', rating=8.8)

In [ ]:
from pydantic import BaseModel, Field
from typing import Literal

# Structured Output 정의
class EmailAnalysis(BaseModel):
    """이메일 내용을 분석한 결과 구조."""
    intent: Literal["complaint", "inquiry", "confirmation", "other"] = Field(
        description="이메일의 주요 의도 (예: complaint=불만, inquiry=문의, confirmation=확인, other=기타)"
    )
    sentiment: Literal["positive", "negative", "neutral"] = Field(description="이메일의 감정 상태")
    summary: str = Field(description="이메일 내용 요약")
    next_action: str = Field(description="에이전트가 수행해야 할 다음 단계 (예: 회신, 확인, 무시 등)")

In [ ]:
from langchain.agents import create_agent
from langchain.agents.structured_output import ToolStrategy

# response_format
agent = create_agent(
    model="gpt-5.4-mini",
    tools=[],
    response_format = ToolStrategy(EmailAnalysis)
)

In [ ]:
response = agent.invoke(
    {
        "messages": [
            {"role": "system", "content": "최근 온 메일 확인하고 고객의 의도와 감정, 요약, 그리고 어떤 행동이 필요한지 분석하세요."},
            {"role" : "user", "content" :
"""
제목: 구매한 무선 이어폰 한쪽이 작동하지 않습니다

안녕하세요.

지난주에 귀사 쇼핑몰에서 무선 이어폰을 구매했습니다.
그런데 제품을 받은 첫날부터 왼쪽 이어폰이 전혀 충전되지 않고 소리도 나지 않습니다.

처음에는 제가 사용법을 잘못 알고 있는 줄 알고 설명서를 다시 읽고,
충전 케이스도 여러 번 확인했습니다.
하지만 아무리 해도 왼쪽 이어폰만 작동하지 않습니다.

새 제품을 구매했는데 처음부터 불량이라 매우 실망스럽습니다.
빠른 교환 또는 환불 처리를 요청드립니다.

주문번호는 A2026-0610-1357입니다.

빠른 답변 부탁드립니다.
"""
}
        ]
    }
)

In [ ]:
response

{'messages': [SystemMessage(content='최근 온 메일 확인하고 고객의 의도와 감정, 요약, 그리고 어떤 행동이 필요한지 분석하세요.', additional_kwargs={}, response_metadata={}, id='651e2875-3446-41f2-a1d5-b3d00a0eeef1'),
  HumanMessage(content='\n제목: 구매한 무선 이어폰 한쪽이 작동하지 않습니다\n\n안녕하세요.\n\n지난주에 귀사 쇼핑몰에서 무선 이어폰을 구매했습니다.\n그런데 제품을 받은 첫날부터 왼쪽 이어폰이 전혀 충전되지 않고 소리도 나지 않습니다.\n\n처음에는 제가 사용법을 잘못 알고 있는 줄 알고 설명서를 다시 읽고,\n충전 케이스도 여러 번 확인했습니다.\n하지만 아무리 해도 왼쪽 이어폰만 작동하지 않습니다.\n\n새 제품을 구매했는데 처음부터 불량이라 매우 실망스럽습니다.\n빠른 교환 또는 환불 처리를 요청드립니다.\n\n주문번호는 A2026-0610-1357입니다.\n\n빠른 답변 부탁드립니다.\n', additional_kwargs={}, response_metadata={}, id='fa410cff-8d53-4047-b99d-f83c99915533'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 137, 'prompt_tokens': 416, 'total_tokens': 553, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.4-mini-2026-03-17', 'system_fingerprint': None, 'id': 'chatcmpl-EXi8pjteSpJTlyL1m1QMHjtWWxzSd', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--01a129d5-5971-7ef0-a67a-9b045d7b32fe-0', tool_calls=[{'name': 'EmailAnalysis', 'args': {'intent': 'complaint', 'sentiment': 'negative', 'summary': '지난주 쇼핑몰에서 구매한 무선 이어폰의 왼쪽 이어폰이 처음부터 충전되지 않고 소리도 나지 않는 불량 문제를 접수했으며, 주문번호 A2026-0610-1357 기준으로 빠른 교환 또는 환불을 요청함.', 'next_action': '고객에게 불량 접수에 대한 사과와 함께 교환/환불 가능 여부를 안내하고, 주문번호를 확인한 뒤 반품/교환 절차를 즉시 진행해야 함.'}, 'id': 'call_M2rdopjwyrE2ry2V1VA8aaTH', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 416, 'output_tokens': 137, 'total_tokens': 553, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content="Returning structured response: intent='complaint' sentiment='negative' summary='지난주 쇼핑몰에서 구매한 무선 이어폰의 왼쪽 이어폰이 처음부터 충전되지 않고 소리도 나지 않는 불량 문제를 접수했으며, 주문번호 A2026-0610-1357 기준으로 빠른 교환 또는 환불을 요청함.' next_action='고객에게 불량 접수에 대한 사과와 함께 교환/환불 가능 여부를 안내하고, 주문번호를 확인한 뒤 반품/교환 절차를 즉시 진행해야 함.'", name='EmailAnalysis', id='044b8c1e-a6ac-4828-a22c-a811c0218319', tool_call_id='call_M2rdopjwyrE2ry2V1VA8aaTH')],
 'structured_response': EmailAnalysis(intent='complaint', sentiment='negative', summary='지난주 쇼핑몰에서 구매한 무선 이어폰의 왼쪽 이어폰이 처음부터 충전되지 않고 소리도 나지 않는 불량 문제를 접수했으며, 주문번호 A2026-0610-1357 기준으로 빠른 교환 또는 환불을 요청함.', next_action='고객에게 불량 접수에 대한 사과와 함께 교환/환불 가능 여부를 안내하고, 주문번호를 확인한 뒤 반품/교환 절차를 즉시 진행해야 함.')}

In [ ]:
response["structured_response"]

EmailAnalysis(intent='complaint', sentiment='negative', summary='지난주 쇼핑몰에서 구매한 무선 이어폰의 왼쪽 이어폰이 처음부터 충전되지 않고 소리도 나지 않는 불량 문제를 접수했으며, 주문번호 A2026-0610-1357 기준으로 빠른 교환 또는 환불을 요청함.', next_action='고객에게 불량 접수에 대한 사과와 함께 교환/환불 가능 여부를 안내하고, 주문번호를 확인한 뒤 반품/교환 절차를 즉시 진행해야 함.')

#### 실습

**고객 컴플레인 분석 Agent 구현**

`complaints_input.csv` 파일에는 고객이 접수한 컴플레인 데이터가 저장되어 있습니다.

Pandas와 LangChain을 사용하여 각 컴플레인을 분석하고, 분석 결과를 원본 데이터에 추가한 뒤 새로운 CSV 파일로 저장하는 프로그램을 작성하세요.

---

**요구사항 1 – CSV 파일 불러오기**

`complaints_input.csv` 파일을 Pandas DataFrame으로 불러오세요.

원본 DataFrame의 사본을 생성하고, 생성한 사본을 조회 Tool에서 사용할 수 있도록 `COMPLAINT_DF` 변수에 저장하세요.

---

**요구사항 2 – 구조화된 분석 결과 정의**

Pydantic의 `BaseModel`을 사용하여 컴플레인 분석 결과의 구조를 정의하세요.

분석 결과에는 다음 필드가 포함되어야 합니다.

| 필드                | 설명                      |
| ----------------- | ----------------------- |
| `intent`          | 고객이 컴플레인을 접수한 핵심 의도     |
| `emotion`         | 고객의 주요 감정 상태            |
| `summary`         | 컴플레인 내용을 1~2문장으로 요약한 결과 |
| `next_action`     | 고객센터의 다음 행동             |
| `priority`        | 처리 우선순위                 |
| `reason`          | 분석 결과를 그렇게 판단한 이유       |
| `suggested_reply` | 고객에게 보낼 짧은 답변 초안        |

`next_action`은 반드시 다음 값 중 하나여야 합니다.

- 회신, 확인, 무시

`priority`는 반드시 다음 값 중 하나여야 합니다.

- 높음, 보통, 낮음

---

**요구사항 3 – 컴플레인 조회 Tool 구현**

사용자가 전달한 `complaint_id`와 일치하는 컴플레인 데이터를 조회하는 LangChain Tool을 구현하세요.

Tool 함수의 이름은 `get_complaint_by_id`로 작성하세요.

Tool은 다음 조건을 만족해야 합니다.

* 정수형 `complaint_id`를 입력받습니다.
* DataFrame의 `complaint_id` 컬럼에서 일치하는 데이터를 조회합니다.
* 조회 결과가 존재하면 첫 번째 행을 선택합니다.
* 결측값은 빈 문자열로 처리합니다.
* 조회 결과를 JSON 문자열로 변환하여 반환합니다.
* 한글이 유니코드 코드로 변환되지 않도록 처리합니다.
* 해당 ID가 없으면 `NOT_FOUND` 오류 정보를 JSON 문자열로 반환합니다.

---

**요구사항 4 – 컴플레인 분석 Agent 생성**

다음 기능을 수행하는 LangChain Agent를 생성하세요.

1. 사용자가 `complaint_id`를 전달하면 `get_complaint_by_id` Tool을 호출합니다.
2. Tool을 통해 조회한 컴플레인 내용만 사용하여 분석합니다.
3. 조회되지 않은 정보는 임의로 추측하지 않습니다.
4. 분석 결과는 요구사항 2에서 정의한 Pydantic 모델의 구조로 반환합니다.

Agent는 다음 기준에 따라 `next_action`을 판단해야 합니다.

* `회신`: 고객에게 안내, 사과 또는 추가 정보 요청이 필요한 경우
* `확인`: 주문, 배송, 환불, 재고, 제품 상태 또는 AS 가능 여부를 내부적으로 확인해야 하는 경우
* `무시`: 구매 사실이나 구체적인 요청이 없고 실제로 처리할 내용이 없는 경우

Agent는 다음 기준에 따라 `priority`를 판단해야 합니다.

* `높음`: 제품 파손, 안전 문제, 부작용, 환불 지연, 즉시 사용 불가
* `보통`: 배송 지연, 구성품 누락, 일반 교환·반품·AS 문의
* `낮음`: 처리할 수 없는 비구매성 비난 또는 정보가 거의 없는 경우

---

**요구사항 5 – 컴플레인 분석 함수 구현**

컴플레인을 분석하는 함수 `analyze_one_complaint(complaint_id)`
를 작성하세요.


함수는 다음 작업을 수행해야 합니다.

1. Agent에 `complaint_id` 분석을 요청합니다.
2. Agent 실행 결과에서 구조화된 응답을 가져옵니다.
3. Pydantic 객체를 Python 딕셔너리로 변환합니다.
4. 추후 기존 DataFrame과 Merge하기 위해, 분석 결과에 원본 `complaint_id`를 추가합니다.
5. 최종 딕셔너리를 반환합니다.

---

**요구사항 6 – 전체 컴플레인 분석**

원본 DataFrame의 모든 `complaint_id`를 순회하면서 `analyze_one_complaint()` 함수를 실행하세요.

각 컴플레인의 분석 결과를 리스트에 저장한 뒤, 별도의 DataFrame으로 변환하여 `analysis_df` 변수에 저장하세요.

`analysis_df`에는 다음 컬럼이 포함되어야 합니다.

```text
complaint_id
intent
emotion
summary
next_action
priority
reason
suggested_reply
```

---

**요구사항 7 – 원본 데이터와 분석 결과 병합**

원본 DataFrame과 `analysis_df`를 `complaint_id` 컬럼을 기준으로 병합하세요.

병합 조건은 다음과 같습니다.

* 원본 DataFrame을 기준으로 모든 행을 유지합니다.
* 병합 기준 컬럼은 `complaint_id`입니다.
* 분석 결과 컬럼을 원본 데이터의 오른쪽에 추가합니다.

최종 DataFrame의 컬럼 순서는 다음과 같이 구성하세요.

```text
complaint_id
customer_name
email
product_name
purchase_channel
order_id
received_date
complaint_text
intent
emotion
priority
next_action
summary
reason
suggested_reply
```

---

**요구사항 8 – 분석 결과 저장**

최종 DataFrame을 다음 파일명으로 저장하세요.

```text
complaints_analyzed.csv
```

CSV 파일을 저장할 때 DataFrame의 인덱스는 포함하지 마세요.

In [ ]:
# 1) CSV 로드
import pandas as pd

CSV_PATH = "complaints_input.csv"

df = pd.read_csv(CSV_PATH)

In [ ]:
df.head()

,complaint_id,customer_name,email,product_name,purchase_channel,order_id,received_date,complaint_text
0,1,한지민,jimin.han@example.com,무선 이어폰 AirBeat X2,자사몰,A2026-0601-1001,2026-06-04,제품을 받자마자 사용해 봤는데 왼쪽 이어폰이 충전도 안 되고 소리도 나지 않습니다....
1,2,박도윤,doyun.park@example.com,공기청정기 PureHome 300,오픈마켓,B2026-0603-2208,NaN,공기청정기를 주문한 지 5일이 지났는데 아직 배송 준비 중으로만 보입니다. 아이 방...
2,3,이서연,seoyeon.lee@example.com,블렌더 MixPro Lite,자사몰,C2026-0602-3391,2026-06-06,어제 블렌더를 받았는데 박스를 열어 보니 뚜껑 부분이 깨져 있었습니다. 외부 박스도...
3,4,최민준,minjun.choi@example.com,스마트 워치 FitNow S,자사몰,D2026-0528-4482,2026-05-31,스마트 워치가 휴대폰 앱과 연결된 후에도 계속 끊깁니다. 운동 기록이 중간에 사라져...
4,5,정하은,haeun.jung@example.com,린넨 셔츠 Summer Linen,자사몰,E2026-0604-5507,2026-06-07,상세페이지 사진에서는 아이보리색처럼 보였는데 실제로는 누런 베이지색에 가깝습니다. ...

In [ ]:
# 사본 생성
COMPLAINT_DF = df.copy()

In [ ]:
# 2) 스키마 정의

from typing import Literal
from pydantic import BaseModel, Field

class ComplaintAnalysis(BaseModel):
    intent: str = Field(description="고객이 이메일을 보낸 핵심 의도")
    emotion: str = Field(description="고객의 감정 상태. 예: 화남, 실망, 불안, 답답함, 중립")
    summary: str = Field(description="컴플레인 내용 1~2문장 요약")
    next_action: Literal["회신", "확인", "무시"] = Field(
        description="고객센터의 다음 행동"
    )
    priority: Literal["높음", "보통", "낮음"] = Field(
        description="처리 우선순위"
    )
    reason: str = Field(description="intent, next_action, priority를 그렇게 판단한 이유")
    suggested_reply: str = Field(description="고객에게 보낼 짧은 답변 초안")

In [ ]:
# 3) Tool 정의
import json
from langchain.tools import tool

@tool
def get_complaint_by_id(complaint_id: int) -> str:
    """
    complaint_id에 해당하는 고객 컴플레인 데이터를 CSV에서 조회합니다.
    반환값은 Agent가 읽기 쉬운 JSON 문자열입니다.
    """
    matched = COMPLAINT_DF[COMPLAINT_DF["complaint_id"] == complaint_id]

    if matched.empty:
        return json.dumps(
            {
                "error": "NOT_FOUND",
                "message": f"complaint_id={complaint_id} 데이터를 찾을 수 없습니다.",
            },
            ensure_ascii=False,
        )

    row = matched.iloc[0].fillna("").to_dict()

    return json.dumps(row, ensure_ascii=False)

In [ ]:
# 4) Agent 생성

agent = create_agent(
    model="gpt-5.4-mini",
    tools=[get_complaint_by_id],
    response_format=ComplaintAnalysis,
    system_prompt="""
너는 고객센터 컴플레인 분류 Agent다.

반드시 get_complaint_by_id Tool을 호출해서 고객 컴플레인 데이터를 조회한 뒤 분석해라.
사용자가 complaint_id를 주면, 그 ID의 데이터만 Tool로 조회해서 판단해라.
CSV에 없는 정보는 추측하지 마라.

분석 필드:
- intent: 고객의 핵심 의도
- emotion: 고객 감정 상태
- summary: 1~2문장 요약
- next_action: 반드시 "회신", "확인", "무시" 중 하나
- priority: 반드시 "높음", "보통", "낮음" 중 하나
- reason: 판단 근거
- suggested_reply: 고객에게 보낼 짧은 답변 초안

next_action 기준:
- "회신": 고객에게 바로 안내/사과/추가 정보 요청을 보내야 하는 경우
- "확인": 주문, 배송, 환불, 재고, 제품 상태, AS 가능 여부 등 내부 확인이 필요한 경우
- "무시": 구매 사실, 상품, 주문번호, 구체 요청이 없고 실제 처리할 내용이 없는 경우

priority 기준:
- "높음": 제품 파손, 안전/부작용, 환불 지연, 즉시 사용 불가 등 긴급성이 높은 경우
- "보통": 배송 지연, 구성품 누락, 일반 교환/반품/AS 문의
- "낮음": 처리할 수 없는 비구매성 비난 또는 정보가 거의 없는 경우
""",
)

In [ ]:
# 5) 분석 함수 작성
def analyze_one_complaint(complaint_id):
    # 1. Agent에게 보낼 질문 만들기
    user_message = f"complaint_id={complaint_id} 컴플레인을 조회해서 분석해줘."

    # 2. Agent 실행
    result = agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": user_message,
                }
            ]
        }
    )

    # 3. Agent의 구조화된 분석 결과 꺼내기
    structured_response = result["structured_response"]

    # 4. Pydantic 객체를 파이썬 딕셔너리로 변환
    analysis = structured_response.model_dump()

    # 5. 분석 결과에 complaint_id 추가
    analysis["complaint_id"] = complaint_id

    # 6. 최종 결과 반환
    return analysis

In [ ]:
# 6) CSV 분석

analysis_rows = []

for complaint_id in df["complaint_id"].tolist():
    print(f"분석 중: complaint_id={complaint_id}")
    analysis_rows.append(analyze_one_complaint(int(complaint_id)))

analysis_df = pd.DataFrame(analysis_rows)
analysis_df.head()

분석 중: complaint_id=1
분석 중: complaint_id=2
분석 중: complaint_id=3
분석 중: complaint_id=4
분석 중: complaint_id=5
분석 중: complaint_id=6
분석 중: complaint_id=7
분석 중: complaint_id=8
분석 중: complaint_id=9
분석 중: complaint_id=10
분석 중: complaint_id=11
분석 중: complaint_id=12

,intent,emotion,summary,next_action,priority,reason,suggested_reply,complaint_id
0,수령 직후 발생한 초기 불량에 대한 교환 또는 환불 요청,"실망, 분노, 답답함",고객은 무선 이어폰 수령 직후 왼쪽 이어폰이 충전되지 않고 소리도 나지 않는 초기 ...,확인,높음,"구체적인 주문 정보와 제품명, 불량 증상이 있으며 즉시 사용 불가한 초기 불량 및 ...","불편을 드려 죄송합니다. 수령 직후 확인된 불량으로 보이며, 교환/환불 진행을 위해...",1
1,주문한 공기청정기의 배송 지연 원인과 예상 수령일 확인 요청,"답답함, 불안, 다급함","고객은 공기청정기 주문 후 5일이 지났는데도 배송 준비 중 상태라며, 배송 지연 사...",확인,보통,"주문번호와 구체적인 상품 정보가 있으며, 현재 상태가 배송 준비 중이라 재고/출고/...",불편을 드려 죄송합니다. 주문번호 확인 후 재고 및 배송 진행 상태를 바로 확인해 ...,2
2,파손된 제품의 교환 요청,"분노와 불만, 당황스러움",고객은 어제 받은 블렌더의 뚜껑이 깨져 있어 정상 사용이 어렵다고 문의했습니다. 외...,확인,높음,"구매 사실, 주문번호, 파손 상태, 교환 요청이 모두 명확합니다. 제품 파손은 즉시...",불편을 드려 죄송합니다. 파손 상태와 주문 내역 확인 후 교환 가능 여부를 빠르게 ...,3
3,스마트 워치의 연결 끊김 문제 해결과 AS 또는 교환 가능 여부 확인,"불편함, 답답함, 사용 불가로 인한 불만",고객은 스마트 워치가 휴대폰 앱과 계속 끊겨 운동 기록이 사라지는 문제를 겪고 있습...,확인,높음,"제품이 정상적으로 사용되지 않을 정도의 불편이 있고, 운동 기록이 중간에 사라지는 ...",불편을 드려 죄송합니다. 연결 끊김 및 기록 누락 증상에 대해 확인 후 AS 또는 ...,4
4,상품 색상 및 원단이 상세페이지와 달라 보여 반품 가능 여부를 문의함,"실망, 불만","고객은 상세페이지에서 본 색상과 실제 수령한 상품 색상이 다르다고 느끼며, 원단도 ...",확인,보통,"주문번호와 구체적인 상품 정보가 있으며, 반품 가능 여부는 내부 정책과 수령 상품 ...",안녕하세요. 상품 색상 및 원단 관련 불편을 드려 죄송합니다. 반품 가능 여부를 확...,5

In [ ]:
# 7) 원본 데이터 일부와 분석 결과 합치기
final_df = df.merge(analysis_df, on="complaint_id", how="left")

final_columns = [
    "complaint_id",
    "customer_name",
    "email",
    "product_name",
    "purchase_channel",
    "order_id",
    "received_date",
    "complaint_text",
    "intent",
    "emotion",
    "priority",
    "next_action",
    "summary",
    "reason",
    "suggested_reply",
]

final_df = final_df[final_columns]

In [ ]:
# 8) 결과 CSV 저장
OUTPUT_PATH = "complaints_analyzed.csv"
final_df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8")

print(f"저장 완료: {OUTPUT_PATH}")
final_df.head()

저장 완료: complaints_analyzed.csv

,complaint_id,customer_name,email,product_name,purchase_channel,order_id,received_date,complaint_text,intent,emotion,priority,next_action,summary,reason,suggested_reply
0,1,한지민,jimin.han@example.com,무선 이어폰 AirBeat X2,자사몰,A2026-0601-1001,2026-06-04,제품을 받자마자 사용해 봤는데 왼쪽 이어폰이 충전도 안 되고 소리도 나지 않습니다....,수령 직후 발생한 초기 불량에 대한 교환 또는 환불 요청,"실망, 분노, 답답함",높음,확인,고객은 무선 이어폰 수령 직후 왼쪽 이어폰이 충전되지 않고 소리도 나지 않는 초기 ...,"구체적인 주문 정보와 제품명, 불량 증상이 있으며 즉시 사용 불가한 초기 불량 및 ...","불편을 드려 죄송합니다. 수령 직후 확인된 불량으로 보이며, 교환/환불 진행을 위해..."
1,2,박도윤,doyun.park@example.com,공기청정기 PureHome 300,오픈마켓,B2026-0603-2208,NaN,공기청정기를 주문한 지 5일이 지났는데 아직 배송 준비 중으로만 보입니다. 아이 방...,주문한 공기청정기의 배송 지연 원인과 예상 수령일 확인 요청,"답답함, 불안, 다급함",보통,확인,"고객은 공기청정기 주문 후 5일이 지났는데도 배송 준비 중 상태라며, 배송 지연 사...","주문번호와 구체적인 상품 정보가 있으며, 현재 상태가 배송 준비 중이라 재고/출고/...",불편을 드려 죄송합니다. 주문번호 확인 후 재고 및 배송 진행 상태를 바로 확인해 ...
2,3,이서연,seoyeon.lee@example.com,블렌더 MixPro Lite,자사몰,C2026-0602-3391,2026-06-06,어제 블렌더를 받았는데 박스를 열어 보니 뚜껑 부분이 깨져 있었습니다. 외부 박스도...,파손된 제품의 교환 요청,"분노와 불만, 당황스러움",높음,확인,고객은 어제 받은 블렌더의 뚜껑이 깨져 있어 정상 사용이 어렵다고 문의했습니다. 외...,"구매 사실, 주문번호, 파손 상태, 교환 요청이 모두 명확합니다. 제품 파손은 즉시...",불편을 드려 죄송합니다. 파손 상태와 주문 내역 확인 후 교환 가능 여부를 빠르게 ...
3,4,최민준,minjun.choi@example.com,스마트 워치 FitNow S,자사몰,D2026-0528-4482,2026-05-31,스마트 워치가 휴대폰 앱과 연결된 후에도 계속 끊깁니다. 운동 기록이 중간에 사라져...,스마트 워치의 연결 끊김 문제 해결과 AS 또는 교환 가능 여부 확인,"불편함, 답답함, 사용 불가로 인한 불만",높음,확인,고객은 스마트 워치가 휴대폰 앱과 계속 끊겨 운동 기록이 사라지는 문제를 겪고 있습...,"제품이 정상적으로 사용되지 않을 정도의 불편이 있고, 운동 기록이 중간에 사라지는 ...",불편을 드려 죄송합니다. 연결 끊김 및 기록 누락 증상에 대해 확인 후 AS 또는 ...
4,5,정하은,haeun.jung@example.com,린넨 셔츠 Summer Linen,자사몰,E2026-0604-5507,2026-06-07,상세페이지 사진에서는 아이보리색처럼 보였는데 실제로는 누런 베이지색에 가깝습니다. ...,상품 색상 및 원단이 상세페이지와 달라 보여 반품 가능 여부를 문의함,"실망, 불만",보통,확인,"고객은 상세페이지에서 본 색상과 실제 수령한 상품 색상이 다르다고 느끼며, 원단도 ...","주문번호와 구체적인 상품 정보가 있으며, 반품 가능 여부는 내부 정책과 수령 상품 ...",안녕하세요. 상품 색상 및 원단 관련 불편을 드려 죄송합니다. 반품 가능 여부를 확...

In [ ]:
from google.colab import files

files.download(OUTPUT_PATH)

## 참고자료

### 랭스미스

In [ ]:
!pip install -U langchain langchain-openai

In [ ]:
import os

# 1. 랭스미스 추적 기능 켜기
os.environ["LANGCHAIN_TRACING_V2"] = "true"

# 2. 랭스미스 API 키 설정
os.environ["LANGCHAIN_API_KEY"] = ""

# 3. 프로젝트 생성
os.environ["LANGCHAIN_PROJECT"] = "My_First_Agent"

In [ ]:
from langchain.chat_models import init_chat_model

model = init_chat_model("gpt-5.4-mini")

In [ ]:
response = model.invoke("랭스미스가 무엇인지 한 문장으로 설명해줘.")
print(f"답변: {response.content}")